
// Objective-C API for talking to the following Go packages
//
//	example.com/emailParser/emailParser
//
// File is generated by gomobile bind. Do not edit.
#ifndef __HTMLEmailParser_FRAMEWORK_H__
#define __HTMLEmailParser_FRAMEWORK_H__

#include "Emailparser.objc.h"
#include "Universe.objc.h"

#endif
