// This file was autogenerated by some hot garbage in the `uniffi` crate.
// Trust me, you don't want to mess with it!

#pragma once

#include <stdbool.h>
#include <stddef.h>
#include <stdint.h>

// The following structs are used to implement the lowest level
// of the FFI, and thus useful to multiple uniffied crates.
// We ensure they are declared exactly once, with a header guard, UNIFFI_SHARED_H.
#ifdef UNIFFI_SHARED_H
    // We also try to prevent mixing versions of shared uniffi header structs.
    // If you add anything to the #else block, you must increment the version suffix in UNIFFI_SHARED_HEADER_V4
    #ifndef UNIFFI_SHARED_HEADER_V4
        #error Combining helper code from multiple versions of uniffi is not supported
    #endif // ndef UNIFFI_SHARED_HEADER_V4
#else
#define UNIFFI_SHARED_H
#define UNIFFI_SHARED_HEADER_V4
// ⚠️ Attention: If you change this #else block (ending in `#endif // def UNIFFI_SHARED_H`) you *must* ⚠️
// ⚠️ increment the version suffix in all instances of UNIFFI_SHARED_HEADER_V4 in this file.           ⚠️

typedef struct RustBuffer
{
    int32_t capacity;
    int32_t len;
    uint8_t *_Nullable data;
} RustBuffer;

typedef int32_t (*ForeignCallback)(uint64_t, int32_t, const uint8_t *_Nonnull, int32_t, RustBuffer *_Nonnull);

typedef struct ForeignBytes
{
    int32_t len;
    const uint8_t *_Nullable data;
} ForeignBytes;

// Error definitions
typedef struct RustCallStatus {
    int8_t code;
    RustBuffer errorBuf;
} RustCallStatus;

// ⚠️ Attention: If you change this #else block (ending in `#endif // def UNIFFI_SHARED_H`) you *must* ⚠️
// ⚠️ increment the version suffix in all instances of UNIFFI_SHARED_HEADER_V4 in this file.           ⚠️
#endif // def UNIFFI_SHARED_H

// Continuation callback for UniFFI Futures
typedef void (*UniFfiRustFutureContinuation)(void * _Nonnull, int8_t);

// Scaffolding functions
void*_Nonnull uniffi_proton_mail_uniffi_fn_clone_loginflow(void*_Nonnull ptr, RustCallStatus *_Nonnull out_status
);
void uniffi_proton_mail_uniffi_fn_free_loginflow(void*_Nonnull ptr, RustCallStatus *_Nonnull out_status
);
int8_t uniffi_proton_mail_uniffi_fn_method_loginflow_is_awaiting_2fa(void*_Nonnull ptr, RustCallStatus *_Nonnull out_status
);
int8_t uniffi_proton_mail_uniffi_fn_method_loginflow_is_logged_in(void*_Nonnull ptr, RustCallStatus *_Nonnull out_status
);
void* _Nonnull uniffi_proton_mail_uniffi_fn_method_loginflow_login(void*_Nonnull ptr, RustBuffer email, RustBuffer password
);
void* _Nonnull uniffi_proton_mail_uniffi_fn_method_loginflow_submit_totp(void*_Nonnull ptr, RustBuffer code
);
void*_Nonnull uniffi_proton_mail_uniffi_fn_method_loginflow_to_user_context(void*_Nonnull ptr, RustCallStatus *_Nonnull out_status
);
void*_Nonnull uniffi_proton_mail_uniffi_fn_clone_maillabelslivequery(void*_Nonnull ptr, RustCallStatus *_Nonnull out_status
);
void uniffi_proton_mail_uniffi_fn_free_maillabelslivequery(void*_Nonnull ptr, RustCallStatus *_Nonnull out_status
);
void uniffi_proton_mail_uniffi_fn_method_maillabelslivequery_disconnect(void*_Nonnull ptr, RustCallStatus *_Nonnull out_status
);
RustBuffer uniffi_proton_mail_uniffi_fn_method_maillabelslivequery_value(void*_Nonnull ptr, RustCallStatus *_Nonnull out_status
);
void*_Nonnull uniffi_proton_mail_uniffi_fn_clone_mailsession(void*_Nonnull ptr, RustCallStatus *_Nonnull out_status
);
void uniffi_proton_mail_uniffi_fn_free_mailsession(void*_Nonnull ptr, RustCallStatus *_Nonnull out_status
);
void*_Nonnull uniffi_proton_mail_uniffi_fn_constructor_mailsession_new(RustBuffer session_dir, RustBuffer user_dir, RustBuffer log_dir, int8_t log_debug, uint64_t key_chain, RustBuffer network_callback, RustCallStatus *_Nonnull out_status
);
int8_t uniffi_proton_mail_uniffi_fn_method_mailsession_is_network_connected(void*_Nonnull ptr, RustCallStatus *_Nonnull out_status
);
void*_Nonnull uniffi_proton_mail_uniffi_fn_method_mailsession_new_login_flow(void*_Nonnull ptr, RustBuffer cb, RustCallStatus *_Nonnull out_status
);
void uniffi_proton_mail_uniffi_fn_method_mailsession_set_network_connected(void*_Nonnull ptr, int8_t online, RustCallStatus *_Nonnull out_status
);
RustBuffer uniffi_proton_mail_uniffi_fn_method_mailsession_stored_sessions(void*_Nonnull ptr, RustCallStatus *_Nonnull out_status
);
void*_Nonnull uniffi_proton_mail_uniffi_fn_method_mailsession_user_context_from_session(void*_Nonnull ptr, void*_Nonnull session, RustBuffer cb, RustCallStatus *_Nonnull out_status
);
void*_Nonnull uniffi_proton_mail_uniffi_fn_clone_mailusersession(void*_Nonnull ptr, RustCallStatus *_Nonnull out_status
);
void uniffi_proton_mail_uniffi_fn_free_mailusersession(void*_Nonnull ptr, RustCallStatus *_Nonnull out_status
);
void* _Nonnull uniffi_proton_mail_uniffi_fn_method_mailusersession_execute_pending_action(void*_Nonnull ptr
);
void* _Nonnull uniffi_proton_mail_uniffi_fn_method_mailusersession_execute_pending_actions(void*_Nonnull ptr
);
void* _Nonnull uniffi_proton_mail_uniffi_fn_method_mailusersession_initialize(void*_Nonnull ptr, uint64_t cb
);
void* _Nonnull uniffi_proton_mail_uniffi_fn_method_mailusersession_logout(void*_Nonnull ptr
);
RustBuffer uniffi_proton_mail_uniffi_fn_method_mailusersession_mail_settings(void*_Nonnull ptr, RustCallStatus *_Nonnull out_status
);
void*_Nonnull uniffi_proton_mail_uniffi_fn_method_mailusersession_new_folder_labels_observed_query(void*_Nonnull ptr, uint64_t cb, RustCallStatus *_Nonnull out_status
);
void*_Nonnull uniffi_proton_mail_uniffi_fn_method_mailusersession_new_label_labels_observed_query(void*_Nonnull ptr, uint64_t cb, RustCallStatus *_Nonnull out_status
);
void*_Nonnull uniffi_proton_mail_uniffi_fn_method_mailusersession_new_system_labels_observed_query(void*_Nonnull ptr, uint64_t cb, RustCallStatus *_Nonnull out_status
);
void* _Nonnull uniffi_proton_mail_uniffi_fn_method_mailusersession_poll_events(void*_Nonnull ptr
);
void*_Nonnull uniffi_proton_mail_uniffi_fn_clone_mailbox(void*_Nonnull ptr, RustCallStatus *_Nonnull out_status
);
void uniffi_proton_mail_uniffi_fn_free_mailbox(void*_Nonnull ptr, RustCallStatus *_Nonnull out_status
);
void*_Nonnull uniffi_proton_mail_uniffi_fn_constructor_mailbox_inbox(void*_Nonnull ctx, RustCallStatus *_Nonnull out_status
);
void*_Nonnull uniffi_proton_mail_uniffi_fn_constructor_mailbox_new(void*_Nonnull ctx, uint64_t label_id, RustCallStatus *_Nonnull out_status
);
void uniffi_proton_mail_uniffi_fn_method_mailbox_delete_conversations(void*_Nonnull ptr, RustBuffer ids, RustCallStatus *_Nonnull out_status
);
void uniffi_proton_mail_uniffi_fn_method_mailbox_mark_conversations_read(void*_Nonnull ptr, RustBuffer ids, RustCallStatus *_Nonnull out_status
);
void uniffi_proton_mail_uniffi_fn_method_mailbox_mark_conversations_unread(void*_Nonnull ptr, RustBuffer ids, RustCallStatus *_Nonnull out_status
);
void*_Nonnull uniffi_proton_mail_uniffi_fn_method_mailbox_new_conversation_live_query(void*_Nonnull ptr, int64_t limit, uint64_t cb, RustCallStatus *_Nonnull out_status
);
void*_Nonnull uniffi_proton_mail_uniffi_fn_clone_mailboxconversationlivequery(void*_Nonnull ptr, RustCallStatus *_Nonnull out_status
);
void uniffi_proton_mail_uniffi_fn_free_mailboxconversationlivequery(void*_Nonnull ptr, RustCallStatus *_Nonnull out_status
);
void uniffi_proton_mail_uniffi_fn_method_mailboxconversationlivequery_disconnect(void*_Nonnull ptr, RustCallStatus *_Nonnull out_status
);
RustBuffer uniffi_proton_mail_uniffi_fn_method_mailboxconversationlivequery_value(void*_Nonnull ptr, RustCallStatus *_Nonnull out_status
);
void*_Nonnull uniffi_proton_mail_uniffi_fn_clone_storedsession(void*_Nonnull ptr, RustCallStatus *_Nonnull out_status
);
void uniffi_proton_mail_uniffi_fn_free_storedsession(void*_Nonnull ptr, RustCallStatus *_Nonnull out_status
);
RustBuffer uniffi_proton_mail_uniffi_fn_method_storedsession_email(void*_Nonnull ptr, RustCallStatus *_Nonnull out_status
);
RustBuffer uniffi_proton_mail_uniffi_fn_method_storedsession_name(void*_Nonnull ptr, RustCallStatus *_Nonnull out_status
);
RustBuffer uniffi_proton_mail_uniffi_fn_method_storedsession_session_id(void*_Nonnull ptr, RustCallStatus *_Nonnull out_status
);
RustBuffer uniffi_proton_mail_uniffi_fn_method_storedsession_user_id(void*_Nonnull ptr, RustCallStatus *_Nonnull out_status
);
void uniffi_proton_mail_uniffi_fn_init_callback_mailusersessioninitializationcallback(ForeignCallback _Nonnull handle
);
void uniffi_proton_mail_uniffi_fn_init_callback_mailboxbackgroundresult(ForeignCallback _Nonnull handle
);
void uniffi_proton_mail_uniffi_fn_init_callback_mailboxlivequeryupdatedcallback(ForeignCallback _Nonnull handle
);
void uniffi_proton_mail_uniffi_fn_init_callback_networkstatuschanged(ForeignCallback _Nonnull handle
);
void uniffi_proton_mail_uniffi_fn_init_callback_oskeychain(ForeignCallback _Nonnull handle
);
void uniffi_proton_mail_uniffi_fn_init_callback_sessioncallback(ForeignCallback _Nonnull handle
);
RustBuffer uniffi_proton_mail_uniffi_fn_func_locate_blockquote(RustBuffer input, RustCallStatus *_Nonnull out_status
);
RustBuffer ffi_proton_mail_uniffi_rustbuffer_alloc(int32_t size, RustCallStatus *_Nonnull out_status
);
RustBuffer ffi_proton_mail_uniffi_rustbuffer_from_bytes(ForeignBytes bytes, RustCallStatus *_Nonnull out_status
);
void ffi_proton_mail_uniffi_rustbuffer_free(RustBuffer buf, RustCallStatus *_Nonnull out_status
);
RustBuffer ffi_proton_mail_uniffi_rustbuffer_reserve(RustBuffer buf, int32_t additional, RustCallStatus *_Nonnull out_status
);
void ffi_proton_mail_uniffi_rust_future_poll_u8(void* _Nonnull handle, UniFfiRustFutureContinuation _Nonnull callback, void* _Nonnull callback_data
);
void ffi_proton_mail_uniffi_rust_future_cancel_u8(void* _Nonnull handle
);
void ffi_proton_mail_uniffi_rust_future_free_u8(void* _Nonnull handle
);
uint8_t ffi_proton_mail_uniffi_rust_future_complete_u8(void* _Nonnull handle, RustCallStatus *_Nonnull out_status
);
void ffi_proton_mail_uniffi_rust_future_poll_i8(void* _Nonnull handle, UniFfiRustFutureContinuation _Nonnull callback, void* _Nonnull callback_data
);
void ffi_proton_mail_uniffi_rust_future_cancel_i8(void* _Nonnull handle
);
void ffi_proton_mail_uniffi_rust_future_free_i8(void* _Nonnull handle
);
int8_t ffi_proton_mail_uniffi_rust_future_complete_i8(void* _Nonnull handle, RustCallStatus *_Nonnull out_status
);
void ffi_proton_mail_uniffi_rust_future_poll_u16(void* _Nonnull handle, UniFfiRustFutureContinuation _Nonnull callback, void* _Nonnull callback_data
);
void ffi_proton_mail_uniffi_rust_future_cancel_u16(void* _Nonnull handle
);
void ffi_proton_mail_uniffi_rust_future_free_u16(void* _Nonnull handle
);
uint16_t ffi_proton_mail_uniffi_rust_future_complete_u16(void* _Nonnull handle, RustCallStatus *_Nonnull out_status
);
void ffi_proton_mail_uniffi_rust_future_poll_i16(void* _Nonnull handle, UniFfiRustFutureContinuation _Nonnull callback, void* _Nonnull callback_data
);
void ffi_proton_mail_uniffi_rust_future_cancel_i16(void* _Nonnull handle
);
void ffi_proton_mail_uniffi_rust_future_free_i16(void* _Nonnull handle
);
int16_t ffi_proton_mail_uniffi_rust_future_complete_i16(void* _Nonnull handle, RustCallStatus *_Nonnull out_status
);
void ffi_proton_mail_uniffi_rust_future_poll_u32(void* _Nonnull handle, UniFfiRustFutureContinuation _Nonnull callback, void* _Nonnull callback_data
);
void ffi_proton_mail_uniffi_rust_future_cancel_u32(void* _Nonnull handle
);
void ffi_proton_mail_uniffi_rust_future_free_u32(void* _Nonnull handle
);
uint32_t ffi_proton_mail_uniffi_rust_future_complete_u32(void* _Nonnull handle, RustCallStatus *_Nonnull out_status
);
void ffi_proton_mail_uniffi_rust_future_poll_i32(void* _Nonnull handle, UniFfiRustFutureContinuation _Nonnull callback, void* _Nonnull callback_data
);
void ffi_proton_mail_uniffi_rust_future_cancel_i32(void* _Nonnull handle
);
void ffi_proton_mail_uniffi_rust_future_free_i32(void* _Nonnull handle
);
int32_t ffi_proton_mail_uniffi_rust_future_complete_i32(void* _Nonnull handle, RustCallStatus *_Nonnull out_status
);
void ffi_proton_mail_uniffi_rust_future_poll_u64(void* _Nonnull handle, UniFfiRustFutureContinuation _Nonnull callback, void* _Nonnull callback_data
);
void ffi_proton_mail_uniffi_rust_future_cancel_u64(void* _Nonnull handle
);
void ffi_proton_mail_uniffi_rust_future_free_u64(void* _Nonnull handle
);
uint64_t ffi_proton_mail_uniffi_rust_future_complete_u64(void* _Nonnull handle, RustCallStatus *_Nonnull out_status
);
void ffi_proton_mail_uniffi_rust_future_poll_i64(void* _Nonnull handle, UniFfiRustFutureContinuation _Nonnull callback, void* _Nonnull callback_data
);
void ffi_proton_mail_uniffi_rust_future_cancel_i64(void* _Nonnull handle
);
void ffi_proton_mail_uniffi_rust_future_free_i64(void* _Nonnull handle
);
int64_t ffi_proton_mail_uniffi_rust_future_complete_i64(void* _Nonnull handle, RustCallStatus *_Nonnull out_status
);
void ffi_proton_mail_uniffi_rust_future_poll_f32(void* _Nonnull handle, UniFfiRustFutureContinuation _Nonnull callback, void* _Nonnull callback_data
);
void ffi_proton_mail_uniffi_rust_future_cancel_f32(void* _Nonnull handle
);
void ffi_proton_mail_uniffi_rust_future_free_f32(void* _Nonnull handle
);
float ffi_proton_mail_uniffi_rust_future_complete_f32(void* _Nonnull handle, RustCallStatus *_Nonnull out_status
);
void ffi_proton_mail_uniffi_rust_future_poll_f64(void* _Nonnull handle, UniFfiRustFutureContinuation _Nonnull callback, void* _Nonnull callback_data
);
void ffi_proton_mail_uniffi_rust_future_cancel_f64(void* _Nonnull handle
);
void ffi_proton_mail_uniffi_rust_future_free_f64(void* _Nonnull handle
);
double ffi_proton_mail_uniffi_rust_future_complete_f64(void* _Nonnull handle, RustCallStatus *_Nonnull out_status
);
void ffi_proton_mail_uniffi_rust_future_poll_pointer(void* _Nonnull handle, UniFfiRustFutureContinuation _Nonnull callback, void* _Nonnull callback_data
);
void ffi_proton_mail_uniffi_rust_future_cancel_pointer(void* _Nonnull handle
);
void ffi_proton_mail_uniffi_rust_future_free_pointer(void* _Nonnull handle
);
void*_Nonnull ffi_proton_mail_uniffi_rust_future_complete_pointer(void* _Nonnull handle, RustCallStatus *_Nonnull out_status
);
void ffi_proton_mail_uniffi_rust_future_poll_rust_buffer(void* _Nonnull handle, UniFfiRustFutureContinuation _Nonnull callback, void* _Nonnull callback_data
);
void ffi_proton_mail_uniffi_rust_future_cancel_rust_buffer(void* _Nonnull handle
);
void ffi_proton_mail_uniffi_rust_future_free_rust_buffer(void* _Nonnull handle
);
RustBuffer ffi_proton_mail_uniffi_rust_future_complete_rust_buffer(void* _Nonnull handle, RustCallStatus *_Nonnull out_status
);
void ffi_proton_mail_uniffi_rust_future_poll_void(void* _Nonnull handle, UniFfiRustFutureContinuation _Nonnull callback, void* _Nonnull callback_data
);
void ffi_proton_mail_uniffi_rust_future_cancel_void(void* _Nonnull handle
);
void ffi_proton_mail_uniffi_rust_future_free_void(void* _Nonnull handle
);
void ffi_proton_mail_uniffi_rust_future_complete_void(void* _Nonnull handle, RustCallStatus *_Nonnull out_status
);
uint16_t uniffi_proton_mail_uniffi_checksum_func_locate_blockquote(void
    
);
uint16_t uniffi_proton_mail_uniffi_checksum_method_loginflow_is_awaiting_2fa(void
    
);
uint16_t uniffi_proton_mail_uniffi_checksum_method_loginflow_is_logged_in(void
    
);
uint16_t uniffi_proton_mail_uniffi_checksum_method_loginflow_login(void
    
);
uint16_t uniffi_proton_mail_uniffi_checksum_method_loginflow_submit_totp(void
    
);
uint16_t uniffi_proton_mail_uniffi_checksum_method_loginflow_to_user_context(void
    
);
uint16_t uniffi_proton_mail_uniffi_checksum_method_maillabelslivequery_disconnect(void
    
);
uint16_t uniffi_proton_mail_uniffi_checksum_method_maillabelslivequery_value(void
    
);
uint16_t uniffi_proton_mail_uniffi_checksum_method_mailsession_is_network_connected(void
    
);
uint16_t uniffi_proton_mail_uniffi_checksum_method_mailsession_new_login_flow(void
    
);
uint16_t uniffi_proton_mail_uniffi_checksum_method_mailsession_set_network_connected(void
    
);
uint16_t uniffi_proton_mail_uniffi_checksum_method_mailsession_stored_sessions(void
    
);
uint16_t uniffi_proton_mail_uniffi_checksum_method_mailsession_user_context_from_session(void
    
);
uint16_t uniffi_proton_mail_uniffi_checksum_method_mailusersession_execute_pending_action(void
    
);
uint16_t uniffi_proton_mail_uniffi_checksum_method_mailusersession_execute_pending_actions(void
    
);
uint16_t uniffi_proton_mail_uniffi_checksum_method_mailusersession_initialize(void
    
);
uint16_t uniffi_proton_mail_uniffi_checksum_method_mailusersession_logout(void
    
);
uint16_t uniffi_proton_mail_uniffi_checksum_method_mailusersession_mail_settings(void
    
);
uint16_t uniffi_proton_mail_uniffi_checksum_method_mailusersession_new_folder_labels_observed_query(void
    
);
uint16_t uniffi_proton_mail_uniffi_checksum_method_mailusersession_new_label_labels_observed_query(void
    
);
uint16_t uniffi_proton_mail_uniffi_checksum_method_mailusersession_new_system_labels_observed_query(void
    
);
uint16_t uniffi_proton_mail_uniffi_checksum_method_mailusersession_poll_events(void
    
);
uint16_t uniffi_proton_mail_uniffi_checksum_method_mailbox_delete_conversations(void
    
);
uint16_t uniffi_proton_mail_uniffi_checksum_method_mailbox_mark_conversations_read(void
    
);
uint16_t uniffi_proton_mail_uniffi_checksum_method_mailbox_mark_conversations_unread(void
    
);
uint16_t uniffi_proton_mail_uniffi_checksum_method_mailbox_new_conversation_live_query(void
    
);
uint16_t uniffi_proton_mail_uniffi_checksum_method_mailboxconversationlivequery_disconnect(void
    
);
uint16_t uniffi_proton_mail_uniffi_checksum_method_mailboxconversationlivequery_value(void
    
);
uint16_t uniffi_proton_mail_uniffi_checksum_method_storedsession_email(void
    
);
uint16_t uniffi_proton_mail_uniffi_checksum_method_storedsession_name(void
    
);
uint16_t uniffi_proton_mail_uniffi_checksum_method_storedsession_session_id(void
    
);
uint16_t uniffi_proton_mail_uniffi_checksum_method_storedsession_user_id(void
    
);
uint16_t uniffi_proton_mail_uniffi_checksum_constructor_mailsession_new(void
    
);
uint16_t uniffi_proton_mail_uniffi_checksum_constructor_mailbox_inbox(void
    
);
uint16_t uniffi_proton_mail_uniffi_checksum_constructor_mailbox_new(void
    
);
uint16_t uniffi_proton_mail_uniffi_checksum_method_mailusersessioninitializationcallback_on_stage(void
    
);
uint16_t uniffi_proton_mail_uniffi_checksum_method_mailboxbackgroundresult_on_background_result(void
    
);
uint16_t uniffi_proton_mail_uniffi_checksum_method_mailboxlivequeryupdatedcallback_on_updated(void
    
);
uint16_t uniffi_proton_mail_uniffi_checksum_method_networkstatuschanged_on_network_status_changed(void
    
);
uint16_t uniffi_proton_mail_uniffi_checksum_method_oskeychain_store(void
    
);
uint16_t uniffi_proton_mail_uniffi_checksum_method_oskeychain_delete(void
    
);
uint16_t uniffi_proton_mail_uniffi_checksum_method_oskeychain_get(void
    
);
uint16_t uniffi_proton_mail_uniffi_checksum_method_sessioncallback_on_session_refresh(void
    
);
uint16_t uniffi_proton_mail_uniffi_checksum_method_sessioncallback_on_session_deleted(void
    
);
uint16_t uniffi_proton_mail_uniffi_checksum_method_sessioncallback_on_refresh_failed(void
    
);
uint16_t uniffi_proton_mail_uniffi_checksum_method_sessioncallback_on_error(void
    
);
uint32_t ffi_proton_mail_uniffi_uniffi_contract_version(void
    
);

