name: ProtonMail

options:
  createIntermediateGroups: true
  dead_code_stripping: true
  generateEmptyDirectories: true
  groupOrdering:
    - pattern: 'Modules'
      order: [App]
  deploymentTarget:
    iOS: "17.2"
  postGenCommand:
    # Copy the File header into the generated xcodeproj bundle.
    cp ./scripts/templates/IDETemplateMacros.plist ProtonMail.xcodeproj/xcshareddata/

packages:
  InboxComposer:
    path: Modules/InboxComposer
    group: Modules
  InboxContacts:
    path: Modules/InboxContacts
    group: Modules
  InboxCore:
    path: Modules/InboxCore
    group: Modules
  InboxCoreUI:
    path: Modules/InboxCoreUI
    group: Modules
  InboxDesignSystem:
    path: Modules/InboxDesignSystem
    group: Modules
  InboxWebView:
    path: Modules/InboxWebView
    group: Modules
  InboxIAP:
    path: Modules/InboxIAP
    group: Modules
  InboxAttribution:
    path: Modules/InboxAttribution
    group: Modules
  InboxKeychain:
    path: Modules/InboxKeychain
    group: Modules
  InboxRSVP:
    path: Modules/InboxRSVP
    group: Modules
  InboxSnapshotTesting:
    path: Modules/InboxSnapshotTesting
    group: Modules
  InboxTesting:
    path: Modules/InboxTesting
    group: Modules
  PaymentsNG:
    path: ProtonPackages/et-protoncore/platform/apple/Payments/PaymentsNG
    group: ProtonPackages
  PaymentsUI:
    path: ProtonPackages/et-protoncore/platform/apple/Payments/PaymentsUI
    group: ProtonPackages
  proton_app_uniffi:
    path: ProtonPackages/proton_app_uniffi
    group: ProtonPackages
  ProtonCoreET:
    path: ProtonPackages/et-protoncore/platform/apple/ProtonCoreET
    group: ProtonPackages
  Scrypt:
    url: https://github.com/greymass/swift-scrypt.git
    revision: "be61ddc3c1efb9cb35de251afa88f4897c6cc255"
  SwiftUIIntrospect:
    url: https://github.com/siteline/swiftui-introspect
    from: "1.4.0-beta.4"
  TestableNotificationService:
    path: Modules/TestableNotificationService
    group: Modules
  TestableShareExtension:
    path: Modules/TestableShareExtension
    group: Modules
  TryCatch:
    path: Modules/TryCatch
    group: Modules
  ViewInspector:
    url: https://github.com/nalexn/ViewInspector.git
    from: "0.10.1"

configs:
  Debug: debug
  QA: release
  AppStore: release

settings:
  base:
    BUNDLE_DISPLAY_NAME: "Proton Mail"
    CODE_SIGN_STYLE: Manual
    CURRENT_PROJECT_VERSION: 1
    DEVELOPMENT_TEAM: 2SB5Z68H26
    MARKETING_VERSION: 7.9.0
    SWIFT_STRICT_CONCURRENCY: complete
  configs:
    Debug:
      OTHER_SWIFT_FLAGS: "-Xfrontend -enable-actor-data-race-checks"
    QA:
      SWIFT_ACTIVE_COMPILATION_CONDITIONS: "QA"

targetTemplates:
  Extension:
    type: app-extension
    platform: iOS
    scheme: {}
    sources:
      - path: Modules/${target_name}/Sources
    settings:
      base:
        CODE_SIGN_IDENTITY: "Apple Distribution: Proton AG (2SB5Z68H26)"
        CODE_SIGN_ENTITLEMENTS: ${target_name}.entitlements
        PRODUCT_BUNDLE_IDENTIFIER: ${bundle_identifier}
        PROVISIONING_PROFILE_SPECIFIER: ${release_provisioning_profile}
      configs:
        Debug:
          CODE_SIGN_IDENTITY: "Apple Development"
          CODE_SIGN_STYLE: Automatic
          PROVISIONING_PROFILE_SPECIFIER: ""
    info:
      path: Modules/${target_name}/Sources/SupportingFiles/Info.plist
      properties:
        CFBundleDisplayName: "$(BUNDLE_DISPLAY_NAME)"
        CFBundleShortVersionString: "$(MARKETING_VERSION)"
        NSExtension:
          NSExtensionPointIdentifier: ${point_identifier}
          NSExtensionPrincipalClass: $(PRODUCT_MODULE_NAME).${principal_class}

targets:
  ProtonMail:
    type: application
    platform: iOS
    supportedDestinations:
      - iOS
    scheme:
      preActions:
        - name: swift-format
          script: |
            if [ $ACTION == "build" ]; then
              cd "$SRCROOT"
              xcrun swift-format format -r Modules -i
            fi
          settingsTarget: ProtonMail
        - name: Sourcery
          script: |
            if [ $ACTION == "build" ]; then
              cd "$SRCROOT"
              find sourcery/configs -name "*.yaml" -exec /opt/homebrew/bin/mint run sourcery --config {} \;
            fi
          settingsTarget: ProtonMail
    sources:
      - path: Modules/App/Sources
      - path: Settings.bundle
    settings:
      base:
        ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
        ASSETCATALOG_COMPILER_INCLUDE_ALL_APPICON_ASSETS: YES
        PRODUCT_BUNDLE_IDENTIFIER: "ch.protonmail.protonmail"
        PROVISIONING_PROFILE_SPECIFIER: "ProtonMail Release"
        SWIFT_EMIT_LOC_STRINGS: YES
        CODE_SIGN_ENTITLEMENTS: "ProtonMail.entitlements"
        CODE_SIGN_IDENTITY: "Apple Distribution: Proton AG (2SB5Z68H26)"
      configs:
        Debug:
          CODE_SIGN_ENTITLEMENTS: "ProtonMailDebug.entitlements"
          CODE_SIGN_IDENTITY: "Apple Development"
          PROVISIONING_PROFILE_SPECIFIER: "ProtonMail Dev"
        QA:
          CODE_SIGN_ENTITLEMENTS: "ProtonMailDebug.entitlements"
          ASSETCATALOG_COMPILER_APPICON_NAME: AppIconDev
    info:
      path: Modules/App/Sources/SupportingFiles/Info.plist
      properties:
        CFBundleDisplayName: "$(BUNDLE_DISPLAY_NAME)"
        CFBundleShortVersionString: "$(MARKETING_VERSION)"
        CFBundlePackageType: "$(PRODUCT_BUNDLE_PACKAGE_TYPE)"
        CFBundleURLTypes:
          - CFBundleTypeRole: Editor
            CFBundleURLName: ch.protonmail.protonmail
            CFBundleURLSchemes:
              - mailto
              - protonmail
        CFBundleIcons:
          CFBundleAlternateIcons:
            AppIcon-notes:
              CFBundleIconFiles:
                - AppIcon-notes
            AppIcon-weather:
              CFBundleIconFiles:
                - AppIcon-weather
            AppIcon-calculator:
              CFBundleIconFiles:
                - AppIcon-calculator
          CFBundlePrimaryIcon:
            CFBundleIconFiles:
              - AppIcon
            UIPrerenderedIcon: NO
        ITSAppUsesNonExemptEncryption: YES
        ITSEncryptionExportComplianceCode: "d90af253-90ca-4698-95d3-40f4e4a36ce4"
        LSRequiresIPhoneOS: YES
        NSAppTransportSecurity:
          NSAllowsArbitraryLoadsInWebContent: YES
        NSCameraUsageDescription: "{{Placeholder}}"
        NSContactsUsageDescription: "{{Placeholder}}"
        NSFaceIDUsageDescription: "{{Placeholder}}"
        NSPhotoLibraryAddUsageDescription: "{{Placeholder}}"
        UIApplicationSupportsIndirectInputEvents: YES
        UIApplicationSceneManifest:
          UIApplicationSupportsMultipleScenes: YES
        UIDesignRequiresCompatibility: YES
        UILaunchScreen:
          UILaunchScreen: []
        UISupportedInterfaceOrientations:
          - UIInterfaceOrientationPortrait
          - UIInterfaceOrientationPortraitUpsideDown
          - UIInterfaceOrientationLandscapeLeft
          - UIInterfaceOrientationLandscapeRight
        BGTaskSchedulerPermittedIdentifiers:
          - ch.protonmail.protonmail.execute_pending_actions
        UIBackgroundModes: [processing]
        SKAdNetworkItems:
          - SKAdNetworkIdentifier: eqhxz8m8av.skadnetwork
          - SKAdNetworkIdentifier: cstr6suwn9.skadnetwork
          - SKAdNetworkIdentifier: klf5c3l5u5.skadnetwork
          - SKAdNetworkIdentifier: v9wttpbfk9.skadnetwork
          - SKAdNetworkIdentifier: n38lu8286q.skadnetwork
          - SKAdNetworkIdentifier: mj797d8u6f.skadnetwork
          - SKAdNetworkIdentifier: 22mmun2rn5.skadnetwork
          - SKAdNetworkIdentifier: 238da6jt44.skadnetwork
          - SKAdNetworkIdentifier: 2tdux39lx8.skadnetwork
          - SKAdNetworkIdentifier: n66cz3y3bx.skadnetwork
          - SKAdNetworkIdentifier: 9yg77x724h.skadnetwork
    dependencies:
      - package: InboxComposer
      - package: InboxContacts
      - package: InboxCore
      - package: InboxCoreUI
      - package: InboxDesignSystem
      - package: InboxIAP
      - package: InboxKeychain
      - package: InboxAttribution
      - package: InboxRSVP
      - target: NotificationService
      - package: PaymentsUI
      - package: proton_app_uniffi
      - package: ProtonCoreET
        products:
          - AccountChallenge
          - AccountLogin
          - AccountManager
          - AccountPassword
      - package: Scrypt
      - target: ShareExtension
      - package: SwiftUIIntrospect
    preBuildScripts:
      - name: swift-format
        script: xcrun swift-format lint -r Modules
        basedOnDependencyAnalysis: false
      - name: Update Licenses
        script: /opt/homebrew/bin/mint run LicensePlist license-plist --output-path Settings.bundle
        basedOnDependencyAnalysis: false

  ProtonMailTest:
    type: bundle.unit-test
    platform: iOS
    info:
      path: Modules/App/Tests/SupportingFiles/Info.plist
    sources:
      - path: Modules/App/Tests
        excludes:
          - "Modules/App/Tests/**/__Snapshots__"
    dependencies:
      - target: ProtonMail
      - package: InboxSnapshotTesting
      - package: InboxTesting
      - package: ViewInspector
      - package: proton_app_uniffi
    settings:
       SWIFT_OBJC_BRIDGING_HEADER: Modules/App/Tests/Utils/ProtonMailTest-Bridging-Header.h

  ProtonMailUITest:
    type: bundle.ui-testing
    platform: iOS
    info:
      path: Modules/App/UITests/SupportingFiles/Info.plist
    sources:
      - path: Modules/App/UITests
    dependencies:
      - target: ProtonMail
    scheme: ProtonMailUITest

  NotificationService:
    templates:
      - Extension
    templateAttributes:
      bundle_identifier: ch.protonmail.protonmail.notifications
      principal_class: NotificationService
      point_identifier: com.apple.usernotifications.service
      release_provisioning_profile: "Mail - Notification Service Distribution"
    dependencies:
      - package: TestableNotificationService

  ShareExtension:
    templates:
      - Extension
    templateAttributes:
      bundle_identifier: ch.protonmail.protonmail.Share
      principal_class: DeepLinkingShareViewController
      point_identifier: com.apple.share-services
      release_provisioning_profile: "Protonmail share release"
    dependencies:
      - package: TestableShareExtension
    info:
      properties:
        NSExtension:
          NSExtensionAttributes:
            NSExtensionActivationRule: >
              SUBQUERY (
                extensionItems,
                $extensionItem,
                SUBQUERY (
                    $extensionItem.attachments,
                    $attachment,
                    ANY $attachment.registeredTypeIdentifiers UTI-CONFORMS-TO "public.data"
                ).@count > 0
              ).@count > 0

schemes:
  ProtonMailUITest:
    build:
      config: Debug
      targets:
        ProtonMail: all
        ProtonMailUITest: all
    test:
      config: Debug
      targets:
        - ProtonMailUITest
      testPlans:
        - path: Modules/App/UITests/Plans/PerformanceTests.xctestplan
          defaultPlan: true
      gatherCoverageData: true
      parallelizable: true
      randomExecutionOrder: true

  AllUnitAndSnapshotTests:
    build:
      targets:
        ProtonMail: [test, run]
    test:
      testPlans:
        - path: TestPlans/AllUnitAndSnapshotTests.xctestplan

  QA:
    build:
      targets:
        ProtonMail: [run, archive]
    run:
      config: QA
    archive:
      config: QA
