name: ProtonMail

options:
  createIntermediateGroups: true
  dead_code_stripping: true
  generateEmptyDirectories: true
  groupOrdering:
    - pattern: 'Modules'
      order: [App]
  deploymentTarget:
    iOS: "17.2"
  postGenCommand:
    # Copy the File header into the generated xcodeproj bundle.
    cp ./scripts/templates/IDETemplateMacros.plist ProtonMail.xcodeproj/xcshareddata/

packages:
  Collections:
    url: https://github.com/apple/swift-collections.git
    minorVersion: "1.1.2"
  InboxContacts:
    path: Modules/InboxContacts
    group: Modules
  InboxComposer:
    path: Modules/InboxComposer
    group: Modules
  InboxCore:
    path: Modules/InboxCore
    group: Modules
  InboxCoreUI:
    path: Modules/InboxCoreUI
    group: Modules
  InboxDesignSystem:
    path: Modules/InboxDesignSystem
    group: Modules
  InboxKeychain:
    path: Modules/InboxKeychain
    group: Modules
  InboxSnapshotTesting:
    path: Modules/InboxSnapshotTesting
    group: Modules
  InboxTesting:
    path: Modules/InboxTesting
    group: Modules
  Lottie:
    url: https://github.com/airbnb/lottie-ios.git
    minorVersion: "4.5.0"    
  Nimble:
    url: https://github.com/Quick/Nimble
    minorVersion: "13.3.0"
  proton_app_uniffi:
    path: ProtonPackages/proton_app_uniffi
    group: ProtonPackages
  ProtonCoreET:
    path: ProtonPackages/et-protoncore/platform/apple/ProtonCoreET
    group: ProtonPackages
  SwiftNIO:
    url: https://github.com/apple/swift-nio.git
    minorVersion: "2.64.0"
  SwiftNIOHTTP2:
    url: https://github.com/apple/swift-nio-http2.git
    minorVersion: "1.30.0"
  SwiftUIIntrospect:
    url: https://github.com/siteline/swiftui-introspect
    minorVersion: "1.3.0"
  ViewInspector:
    url: https://github.com/nalexn/ViewInspector.git
    minorVersion: "0.9.11"

configs:
  Debug: debug
  Release: release
  UITests: debug

targets:
  ProtonMail:
    type: application 
    platform: iOS
    supportedDestinations:
      - iOS
    deploymentTarget: 17.2
    scheme: {}
    attributes:
      ProvisioningStyle: Manual    
    sources:
      - path: Modules/App/Sources
    settings:
      base:
        ASSETCATALOG_COMPILER_APPICON_NAME: AppIconDev
        ASSETCATALOG_COMPILER_GLOBAL_ACCENT_COLOR_NAME: AccentColor
        BUNDLE_DISPLAY_NAME: "Proton Mail (ET)"
        CODE_SIGN_IDENTITY: "Apple Development"
        CODE_SIGN_STYLE: Automatic
        DEVELOPMENT_TEAM: 2SB5Z68H26
        MARKETING_VERSION: 0.2.0
        CURRENT_PROJECT_VERSION: 16
        PRODUCT_BUNDLE_IDENTIFIER: "me.proton.mail.ios"
        PROVISIONING_PROFILE_SPECIFIER: ""
        SWIFT_EMIT_LOC_STRINGS: YES
        SWIFT_STRICT_CONCURRENCY: "complete"
        CODE_SIGN_ENTITLEMENTS: "ProtonMail.entitlements"
      configs:
        UITests:
          SWIFT_ACTIVE_COMPILATION_CONDITIONS: "UITESTS"
          PM_API_HOST: "proton.black"
        Debug:
          PM_API_HOST: "proton.me"
        Release:
          CODE_SIGN_STYLE: Manual
          CODE_SIGN_IDENTITY: "iPhone Distribution: Proton AG (2SB5Z68H26)"
          PROVISIONING_PROFILE_SPECIFIER: "Mail - Engineering Transformation Distribution"
          PM_API_HOST: "proton.me"
    info: 
      path: Modules/App/Sources/SupportingFiles/Info.plist
      properties:
        CFBundleDisplayName: "$(BUNDLE_DISPLAY_NAME)"
        CFBundleShortVersionString: "$(MARKETING_VERSION)"
        CFBundleVersion: "$(CURRENT_PROJECT_VERSION)"
        CFBundlePackageType: "$(PRODUCT_BUNDLE_PACKAGE_TYPE)"
        PMApiHost: "$(PM_API_HOST)"
        LSRequiresIPhoneOS: YES
        UIApplicationSupportsIndirectInputEvents: YES
        UIApplicationSceneManifest:
          UIApplicationSupportsMultipleScenes: YES
        UILaunchScreen: 
          UILaunchScreen: []
        UISupportedInterfaceOrientations:
          - UIInterfaceOrientationPortrait
        UISupportedInterfaceOrientations~ipad:
          - UIInterfaceOrientationPortrait
          - UIInterfaceOrientationPortraitUpsideDown
          - UIInterfaceOrientationLandscapeLeft
          - UIInterfaceOrientationLandscapeRight
    dependencies:
      - package: Collections
      - package: InboxContacts
      - package: InboxComposer
      - package: InboxCore
      - package: InboxCoreUI
      - package: InboxDesignSystem
      - package: InboxKeychain
      - package: Lottie
      - package: proton_app_uniffi
      - package: ProtonCoreET
        products: 
          - AccountLogin
          - AccountManager
      - package: SwiftUIIntrospect

  ProtonMailTest:
    type: bundle.unit-test
    platform: iOS
    info: 
      path: Modules/App/Tests/SupportingFiles/Info.plist
    sources:
      - path: Modules/App/Tests
        excludes:
          - "Modules/App/Tests/**/__Snapshots__"
    dependencies:
      - target: ProtonMail
      - package: InboxSnapshotTesting
      - package: InboxTesting
      - package: Nimble
      - package: ViewInspector
    scheme:
      gatherCoverageData: true
      testTargets:
        - name: ProtonMailTest
          parallelizable: true
          randomExecutionOrder: true
    settings:
       SWIFT_OBJC_BRIDGING_HEADER: Modules/App/Tests/Utils/ProtonMailTest-Bridging-Header.h

  ProtonMailUITest:
    type: bundle.ui-testing
    platform: iOS
    info: 
      path: Modules/App/UITests/SupportingFiles/Info.plist
    sources:
      - path: Modules/App/UITests
      - path: Modules/App/UITests/NetworkMocks
        type: resources
    dependencies:
      - target: ProtonMail
      - package: SwiftNIO
        product: NIOCore
        product: NIOHTTP1
      - package: SwiftNIOHTTP2 
        product: NIOHTTP2
    settings:
      configs:
        UITests: 
          SWIFT_ACTIVE_COMPILATION_CONDITIONS: "UITESTS"
    scheme: ProtonMailUITest

schemes:
  ProtonMailUITest:
    build:
      config: UITests
      targets:
        ProtonMail: all
        ProtonMailUITest: all
    test:
      config: UITests
      targets:
        - ProtonMailUITest
      testPlans:
        - path: Modules/App/UITests/Plans/SmokeTests.xctestplan
          defaultPlan: true
        - path: Modules/App/UITests/Plans/RegressionTests.xctestplan
      gatherCoverageData: true
      parallelizable: true
      randomExecutionOrder: true
