name: ProtonMail

options:
  createIntermediateGroups: true
  dead_code_stripping: true
  generateEmptyDirectories: true
  groupOrdering:
    - pattern: 'Modules'
      order: [App]
  deploymentTarget:
    iOS: "17.2"
  postGenCommand:
    # Copy the File header into the generated xcodeproj bundle.
    cp ./scripts/templates/IDETemplateMacros.plist ProtonMail.xcodeproj/xcshareddata/

packages:
  InboxComposer:
    path: Modules/InboxComposer
    group: Modules
  InboxContacts:
    path: Modules/InboxContacts
    group: Modules
  InboxCore:
    path: Modules/InboxCore
    group: Modules
  InboxCoreUI:
    path: Modules/InboxCoreUI
    group: Modules
  InboxDesignSystem:
    path: Modules/InboxDesignSystem
    group: Modules
  InboxKeychain:
    path: Modules/InboxKeychain
    group: Modules
  InboxSnapshotTesting:
    path: Modules/InboxSnapshotTesting
    group: Modules
  InboxTesting:
    path: Modules/InboxTesting
    group: Modules
  Lottie:
    url: https://github.com/airbnb/lottie-ios.git
    from: "4.5.0"
  Nimble:
    url: https://github.com/Quick/Nimble
    from: "13.3.0"
  proton_app_uniffi:
    path: ProtonPackages/proton_app_uniffi
    group: ProtonPackages
  ProtonCoreET:
    path: ProtonPackages/et-protoncore/platform/apple/ProtonCoreET
    group: ProtonPackages
  SwiftNIO:
    url: https://github.com/apple/swift-nio.git
    from: "2.64.0"
  SwiftNIOHTTP2:
    url: https://github.com/apple/swift-nio-http2.git
    from: "1.30.0"
  SwiftUIIntrospect:
    url: https://github.com/siteline/swiftui-introspect
    from: "1.3.0"
  TestableNotificationService:
    path: Modules/TestableNotificationService
    group: Modules
  ViewInspector:
    url: https://github.com/nalexn/ViewInspector.git
    from: "0.10.1"

configs:
  Debug: debug
  Release: release
  UITests: debug

settings:
  configs:
    Debug:
      OTHER_SWIFT_FLAGS: "-Xfrontend -enable-actor-data-race-checks"
    UITests:
      OTHER_SWIFT_FLAGS: "-Xfrontend -enable-actor-data-race-checks"

targets:
  ProtonMail:
    type: application
    platform: iOS
    supportedDestinations:
      - iOS
    deploymentTarget: 17.2
    scheme: {}
    attributes:
      ProvisioningStyle: Manual
    sources:
      - path: Modules/App/Sources
    settings:
      base:
        ASSETCATALOG_COMPILER_APPICON_NAME: AppIconDev
        ASSETCATALOG_COMPILER_GLOBAL_ACCENT_COLOR_NAME: AccentColor
        BUNDLE_DISPLAY_NAME: "Proton Mail (ET)"
        CODE_SIGN_IDENTITY: "Apple Development"
        CODE_SIGN_STYLE: Automatic
        DEVELOPMENT_TEAM: 2SB5Z68H26
        MARKETING_VERSION: 0.2.0
        CURRENT_PROJECT_VERSION: 1
        PRODUCT_BUNDLE_IDENTIFIER: "me.proton.mail.ios"
        PROVISIONING_PROFILE_SPECIFIER: ""
        SWIFT_EMIT_LOC_STRINGS: YES
        SWIFT_STRICT_CONCURRENCY: "complete"
        CODE_SIGN_ENTITLEMENTS: "ProtonMail.entitlements"
        SWIFT_ENABLE_OPAQUE_TYPE_ERASURE: NO
      configs:
        UITests:
          SWIFT_ACTIVE_COMPILATION_CONDITIONS: "UITESTS"
          PM_API_HOST: "proton.black"
        Debug:
          PM_API_HOST: "proton.me"
        Release:
          CODE_SIGN_STYLE: Manual
          CODE_SIGN_IDENTITY: "iPhone Distribution: Proton AG (2SB5Z68H26)"
          PROVISIONING_PROFILE_SPECIFIER: "Mail - Engineering Transformation Distribution"
          PM_API_HOST: "proton.me"
    info:
      path: Modules/App/Sources/SupportingFiles/Info.plist
      properties:
        CFBundleDisplayName: "$(BUNDLE_DISPLAY_NAME)"
        CFBundleShortVersionString: "$(MARKETING_VERSION)"
        CFBundleVersion: "$(CURRENT_PROJECT_VERSION)"
        CFBundlePackageType: "$(PRODUCT_BUNDLE_PACKAGE_TYPE)"
        CFBundleURLTypes:
          - CFBundleTypeRole: Editor
            CFBundleURLName: me.proton.mail.ios
            CFBundleURLSchemes:
              - protonmailET
        PMApiHost: "$(PM_API_HOST)"
        LSRequiresIPhoneOS: YES
        NSCameraUsageDescription: "{{Placeholder}}"
        NSContactsUsageDescription: "{{Placeholder}}"
        UIApplicationSupportsIndirectInputEvents: YES
        UIApplicationSceneManifest:
          UIApplicationSupportsMultipleScenes: YES
        UILaunchScreen:
          UILaunchScreen: []
        UISupportedInterfaceOrientations:
          - UIInterfaceOrientationPortrait
        UISupportedInterfaceOrientations~ipad:
          - UIInterfaceOrientationPortrait
          - UIInterfaceOrientationPortraitUpsideDown
          - UIInterfaceOrientationLandscapeLeft
          - UIInterfaceOrientationLandscapeRight
        BGTaskSchedulerPermittedIdentifiers:
          - ch.protonmail.protonmail.execute_pending_actions
        UIBackgroundModes: [processing]
    dependencies:
      - package: InboxComposer
      - package: InboxContacts
      - package: InboxCore
      - package: InboxCoreUI
      - package: InboxDesignSystem
      - package: InboxKeychain
      - package: Lottie
      - target: NotificationService
      - package: proton_app_uniffi
      - package: ProtonCoreET
        products:
          - AccountLogin
          - AccountManager
      - package: SwiftUIIntrospect
    preBuildScripts:
      - name: Sourcery
        script: /opt/homebrew/bin/sourcery --config sourcery/sourcery.yaml

  ProtonMailTest:
    type: bundle.unit-test
    platform: iOS
    info:
      path: Modules/App/Tests/SupportingFiles/Info.plist
    sources:
      - path: Modules/App/Tests
        excludes:
          - "Modules/App/Tests/**/__Snapshots__"
    dependencies:
      - target: ProtonMail
      - package: InboxSnapshotTesting
      - package: InboxTesting
      - package: Nimble
      - package: ViewInspector
      - package: proton_app_uniffi
    settings:
       SWIFT_OBJC_BRIDGING_HEADER: Modules/App/Tests/Utils/ProtonMailTest-Bridging-Header.h

  ProtonMailUITest:
    type: bundle.ui-testing
    platform: iOS
    info:
      path: Modules/App/UITests/SupportingFiles/Info.plist
    sources:
      - path: Modules/App/UITests
      - path: Modules/App/UITests/NetworkMocks
        type: resources
    dependencies:
      - target: ProtonMail
      - package: SwiftNIO
        product: NIOCore
        product: NIOHTTP1
      - package: SwiftNIOHTTP2
        product: NIOHTTP2
    settings:
      configs:
        UITests:
          SWIFT_ACTIVE_COMPILATION_CONDITIONS: "UITESTS"
    scheme: ProtonMailUITest

  NotificationService:
    type: app-extension
    platform: iOS
    dependencies:
      - package: TestableNotificationService
    sources:
      - path: Modules/NotificationService/Sources
    settings:
      base:
        CODE_SIGN_ENTITLEMENTS: "NotificationService.entitlements"
        CODE_SIGN_IDENTITY: "Apple Development"
        CODE_SIGN_STYLE: Automatic
        DEVELOPMENT_TEAM: 2SB5Z68H26
        PRODUCT_BUNDLE_IDENTIFIER: "me.proton.mail.ios.notification-service"
        CURRENT_PROJECT_VERSION: 1
      configs:
        Release:
          CODE_SIGN_STYLE: Manual
          CODE_SIGN_IDENTITY: "iPhone Distribution: Proton AG (2SB5Z68H26)"
          PROVISIONING_PROFILE_SPECIFIER: "ET Mail - Notification Service Distribution"
    info:
      path: Modules/NotificationService/Sources/SupportingFiles/Info.plist
      properties:
        CFBundleDisplayName: "Proton Mail"
        CFBundleVersion: "$(CURRENT_PROJECT_VERSION)"
        NSExtension:
          NSExtensionPointIdentifier: 'com.apple.usernotifications.service'
          NSExtensionPrincipalClass: '$(PRODUCT_MODULE_NAME).NotificationService'

schemes:
  ProtonMailUITest:
    build:
      config: UITests
      targets:
        ProtonMail: all
        ProtonMailUITest: all
    test:
      config: UITests
      targets:
        - ProtonMailUITest
      testPlans:
        - path: Modules/App/UITests/Plans/SmokeTests.xctestplan
          defaultPlan: true
        - path: Modules/App/UITests/Plans/RegressionTests.xctestplan
      gatherCoverageData: true
      parallelizable: true
      randomExecutionOrder: true

  AllUnitAndSnapshotTests:
    build:
      targets:
        ProtonMail: [test, run]
    test:
      debugEnabled: false
      testPlans:
        - path: TestPlans/AllUnitAndSnapshotTests.xctestplan

  NotificationService:
    build:
      targets:
        NotificationService: all
        ProtonMail: all
    run:
      config: Debug
    test:
      config: Debug
    profile:
      config: Release
    analyze:
      config: Debug
    archive:
      config: Release
