name: ProtonMail

options:
  createIntermediateGroups: true
  dead_code_stripping: true
  generateEmptyDirectories: true
  groupOrdering:
    - pattern: 'Modules'
      order: [App]
  deploymentTarget:
    iOS: "17.2"
  postGenCommand:
    # Copy the File header into the generated xcodeproj bundle.
    cp ./scripts/templates/IDETemplateMacros.plist ProtonMail.xcodeproj/xcshareddata/

packages:
  InboxComposer:
    path: Modules/InboxComposer
    group: Modules
  InboxContacts:
    path: Modules/InboxContacts
    group: Modules
  InboxCore:
    path: Modules/InboxCore
    group: Modules
  InboxCoreUI:
    path: Modules/InboxCoreUI
    group: Modules
  InboxDesignSystem:
    path: Modules/InboxDesignSystem
    group: Modules
  InboxKeychain:
    path: Modules/InboxKeychain
    group: Modules
  InboxSnapshotTesting:
    path: Modules/InboxSnapshotTesting
    group: Modules
  InboxTesting:
    path: Modules/InboxTesting
    group: Modules
  Nimble:
    url: https://github.com/Quick/Nimble
    from: "13.3.0"
  proton_app_uniffi:
    path: ProtonPackages/proton_app_uniffi
    group: ProtonPackages
  ProtonCoreET:
    path: ProtonPackages/et-protoncore/platform/apple/ProtonCoreET
    group: ProtonPackages
  Scrypt:
    url: https://github.com/greymass/swift-scrypt.git
    revision: "be61ddc3c1efb9cb35de251afa88f4897c6cc255"
  SwiftNIO:
    url: https://github.com/apple/swift-nio.git
    from: "2.64.0"
  SwiftNIOHTTP2:
    url: https://github.com/apple/swift-nio-http2.git
    from: "1.30.0"
  SwiftUIIntrospect:
    url: https://github.com/siteline/swiftui-introspect
    from: "1.3.0"
  TestableNotificationService:
    path: Modules/TestableNotificationService
    group: Modules
  TestableShareExtension:
    path: Modules/TestableShareExtension
    group: Modules
  TryCatch:
    path: Modules/TryCatch
    group: Modules
  ViewInspector:
    url: https://github.com/nalexn/ViewInspector.git
    from: "0.10.1"

configs:
  Debug: debug
  Release: release
  UITests: debug

settings:
  base:
    BUNDLE_DISPLAY_NAME: "Proton Mail"
    CODE_SIGN_IDENTITY: "Apple Development"
    CODE_SIGN_STYLE: Automatic
    CURRENT_PROJECT_VERSION: 1
    DEVELOPMENT_TEAM: 2SB5Z68H26
    MARKETING_VERSION: 5.1.0
    SWIFT_STRICT_CONCURRENCY: complete
  configs:
    Debug:
      OTHER_SWIFT_FLAGS: "-Xfrontend -enable-actor-data-race-checks"
    Release:
      CODE_SIGN_STYLE: Manual
      CODE_SIGN_IDENTITY: "iPhone Distribution: Proton AG (2SB5Z68H26)"
    UITests:
      OTHER_SWIFT_FLAGS: "-Xfrontend -enable-actor-data-race-checks"

targetTemplates:
  Extension:
    type: app-extension
    platform: iOS
    scheme: {}
    sources:
      - path: Modules/${target_name}/Sources
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: ${bundle_identifier}
        CODE_SIGN_ENTITLEMENTS: ${target_name}.entitlements
      configs:
        Release:
          PROVISIONING_PROFILE_SPECIFIER: ${release_provisioning_profile}
    info:
      path: Modules/${target_name}/Sources/SupportingFiles/Info.plist
      properties:
        CFBundleDisplayName: "$(BUNDLE_DISPLAY_NAME)"
        CFBundleShortVersionString: "$(MARKETING_VERSION)"
        NSExtension:
          NSExtensionPointIdentifier: ${point_identifier}
          NSExtensionPrincipalClass: $(PRODUCT_MODULE_NAME).${principal_class}

targets:
  ProtonMail:
    type: application
    platform: iOS
    supportedDestinations:
      - iOS
    scheme: {}
    sources:
      - path: Modules/App/Sources
    settings:
      base:
        ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
        ASSETCATALOG_COMPILER_GLOBAL_ACCENT_COLOR_NAME: AccentColor
        PRODUCT_BUNDLE_IDENTIFIER: "ch.protonmail.protonmail"
        PROVISIONING_PROFILE_SPECIFIER: ""
        SWIFT_EMIT_LOC_STRINGS: YES
        CODE_SIGN_ENTITLEMENTS: "ProtonMail.entitlements"
        SWIFT_ENABLE_OPAQUE_TYPE_ERASURE: NO
      configs:
        UITests:
          SWIFT_ACTIVE_COMPILATION_CONDITIONS: "UITESTS"
          PM_API_HOST: "proton.black"
        Debug:
          CODE_SIGN_STYLE: Manual
          PROVISIONING_PROFILE_SPECIFIER: "ProtonMail Dev"
          PM_API_HOST: "proton.me"
        Release:
          PROVISIONING_PROFILE_SPECIFIER: "ProtonMail Release"
          PM_API_HOST: "proton.me"
    info:
      path: Modules/App/Sources/SupportingFiles/Info.plist
      properties:
        CFBundleDisplayName: "$(BUNDLE_DISPLAY_NAME)"
        CFBundleShortVersionString: "$(MARKETING_VERSION)"
        CFBundlePackageType: "$(PRODUCT_BUNDLE_PACKAGE_TYPE)"
        CFBundleURLTypes:
          - CFBundleTypeRole: Editor
            CFBundleURLName: ch.protonmail.protonmail
            CFBundleURLSchemes:
              - mailto
              - protonmail
        ITSAppUsesNonExemptEncryption: YES
        ITSEncryptionExportComplianceCode: "d90af253-90ca-4698-95d3-40f4e4a36ce4"
        PMApiHost: "$(PM_API_HOST)"
        LSRequiresIPhoneOS: YES
        NSCameraUsageDescription: "{{Placeholder}}"
        NSContactsUsageDescription: "{{Placeholder}}"
        NSFaceIDUsageDescription: "{{Placeholder}}"
        UIApplicationSupportsIndirectInputEvents: YES
        UIApplicationSceneManifest:
          UIApplicationSupportsMultipleScenes: YES
        UILaunchScreen:
          UILaunchScreen: []
        UISupportedInterfaceOrientations:
          - UIInterfaceOrientationPortrait
        UISupportedInterfaceOrientations~ipad:
          - UIInterfaceOrientationPortrait
          - UIInterfaceOrientationPortraitUpsideDown
          - UIInterfaceOrientationLandscapeLeft
          - UIInterfaceOrientationLandscapeRight
        BGTaskSchedulerPermittedIdentifiers:
          - ch.protonmail.protonmail.execute_pending_actions
        UIBackgroundModes: [processing]
    dependencies:
      - package: InboxComposer
      - package: InboxContacts
      - package: InboxCore
      - package: InboxCoreUI
      - package: InboxDesignSystem
      - package: InboxKeychain
      - target: NotificationService
      - package: proton_app_uniffi
      - package: ProtonCoreET
        products:
          - AccountChallenge
          - AccountLogin
          - AccountManager
      - package: Scrypt
      - target: ShareExtension
      - package: SwiftUIIntrospect
    preBuildScripts:
      - name: swift-format
        script: xcrun swift-format lint -r Modules -p
        basedOnDependencyAnalysis: false
      - name: Sourcery
        script: find sourcery/configs -name "*.yaml" -exec /opt/homebrew/bin/mint run sourcery --config {} \;

  ProtonMailTest:
    type: bundle.unit-test
    platform: iOS
    info:
      path: Modules/App/Tests/SupportingFiles/Info.plist
    sources:
      - path: Modules/App/Tests
        excludes:
          - "Modules/App/Tests/**/__Snapshots__"
    dependencies:
      - target: ProtonMail
      - package: InboxSnapshotTesting
      - package: InboxTesting
      - package: Nimble
      - package: ViewInspector
      - package: proton_app_uniffi
    settings:
       SWIFT_OBJC_BRIDGING_HEADER: Modules/App/Tests/Utils/ProtonMailTest-Bridging-Header.h

  ProtonMailUITest:
    type: bundle.ui-testing
    platform: iOS
    info:
      path: Modules/App/UITests/SupportingFiles/Info.plist
    sources:
      - path: Modules/App/UITests
      - path: Modules/App/UITests/NetworkMocks
        type: resources
    dependencies:
      - target: ProtonMail
      - package: SwiftNIO
        product: NIOCore
        product: NIOHTTP1
      - package: SwiftNIOHTTP2
        product: NIOHTTP2
      - package: Scrypt
    settings:
      configs:
        UITests:
          SWIFT_ACTIVE_COMPILATION_CONDITIONS: "UITESTS"
    scheme: ProtonMailUITest

  NotificationService:
    templates:
      - Extension
    templateAttributes:
      bundle_identifier: ch.protonmail.protonmail.notifications
      principal_class: NotificationService
      point_identifier: com.apple.usernotifications.service
      release_provisioning_profile: "Mail - Notification Service Distribution"
    dependencies:
      - package: TestableNotificationService

  ShareExtension:
    templates:
      - Extension
    templateAttributes:
      bundle_identifier: ch.protonmail.protonmail.Share
      principal_class: ShareViewController
      point_identifier: com.apple.share-services
      release_provisioning_profile: "Mail - Share Extension Distribution"
    dependencies:
      - package: TestableShareExtension
    info:
      properties:
        NSExtension:
          NSExtensionAttributes:
            NSExtensionActivationRule: >
              SUBQUERY (
                extensionItems,
                $extensionItem,
                SUBQUERY (
                    $extensionItem.attachments,
                    $attachment,
                    ANY $attachment.registeredTypeIdentifiers UTI-CONFORMS-TO "public.data"
                ).@count > 0
              ).@count > 0

schemes:
  ProtonMailUITest:
    build:
      config: UITests
      targets:
        ProtonMail: all
        ProtonMailUITest: all
    test:
      config: UITests
      targets:
        - ProtonMailUITest
      testPlans:
        - path: Modules/App/UITests/Plans/SmokeTests.xctestplan
          defaultPlan: true
        - path: Modules/App/UITests/Plans/RegressionTests.xctestplan
      gatherCoverageData: true
      parallelizable: true
      randomExecutionOrder: true

  AllUnitAndSnapshotTests:
    build:
      targets:
        ProtonMail: [test, run]
    test:
      debugEnabled: false
      testPlans:
        - path: TestPlans/AllUnitAndSnapshotTests.xctestplan
