name: ProtonMail

options:
  dead_code_stripping: true
  generateEmptyDirectories: true
  deploymentTarget:
    iOS: "17.2"
  postGenCommand:
    # Copy the File header into the generated xcodeproj bundle.
    cp ./scripts/templates/IDETemplateMacros.plist ProtonMail.xcodeproj/xcshareddata/

packages:
  DesignSystem:
    path: localPackages/DesignSystem
  Keychain:
    path: localPackages/Keychain
  proton_mail_uniffi:
    path: localPackages/proton_mail_uniffi
  SwiftNIO:
    url: https://github.com/apple/swift-nio.git
    minorVersion: "2.64.0"
  SwiftNIOHTTP2:
    url: https://github.com/apple/swift-nio-http2.git
    minorVersion: "1.30.0"
  SwiftUIIntrospect:
    url: https://github.com/siteline/swiftui-introspect
    minorVersion: "1.1.0"
  Nimble:
    url: https://github.com/Quick/Nimble.git
    minorVersion: "13.3.0"

configs:
  Debug: debug
  Release: release
  UITests: debug

targets:
  ProtonMail:
    type: application 
    platform: iOS
    supportedDestinations:
      - iOS
    deploymentTarget: 17.2
    scheme: {}
    attributes:
      ProvisioningStyle: Manual    
    sources:
      - path: ios
    settings:
      base:
        ASSETCATALOG_COMPILER_APPICON_NAME: AppIconDev
        ASSETCATALOG_COMPILER_GLOBAL_ACCENT_COLOR_NAME: AccentColor
        BUNDLE_DISPLAY_NAME: "Proton Mail (ET)"
        CODE_SIGN_IDENTITY: "Apple Development"
        CODE_SIGN_STYLE: Automatic
        DEVELOPMENT_TEAM: 2SB5Z68H26
        MARKETING_VERSION: 0.1.9
        CURRENT_PROJECT_VERSION: 5
        PRODUCT_BUNDLE_IDENTIFIER: "me.proton.mail.ios"
        PROVISIONING_PROFILE_SPECIFIER: ""
        SWIFT_STRICT_CONCURRENCY: "complete"
        CODE_SIGN_ENTITLEMENTS: "ProtonMail.entitlements"
      configs:
        UITests:
          SWIFT_ACTIVE_COMPILATION_CONDITIONS: "UITESTS"
          PM_API_HOST: "proton.black"
        Debug:
          PM_API_HOST: "proton.me"
        Release:
          CODE_SIGN_STYLE: Manual
          CODE_SIGN_IDENTITY: "iPhone Distribution: Proton AG (2SB5Z68H26)"
          PROVISIONING_PROFILE_SPECIFIER: "Mail - Engineering Transformation Distribution"
          PM_API_HOST: "proton.me"
    info: 
      path: ios/Info/Info.plist  
      properties:
        CFBundleDisplayName: "$(BUNDLE_DISPLAY_NAME)"
        CFBundleShortVersionString: "$(MARKETING_VERSION)"
        CFBundleVersion: "$(CURRENT_PROJECT_VERSION)"
        CFBundlePackageType: "$(PRODUCT_BUNDLE_PACKAGE_TYPE)"
        PMApiHost: "$(PM_API_HOST)"
        LSRequiresIPhoneOS: YES
        UIApplicationSupportsIndirectInputEvents: YES
        UIApplicationSceneManifest:
          UIApplicationSupportsMultipleScenes: YES
        UILaunchScreen: 
          UILaunchScreen: []
        UISupportedInterfaceOrientations:
          - UIInterfaceOrientationPortrait
          - UIInterfaceOrientationLandscapeLeft
          - UIInterfaceOrientationLandscapeRight
        UISupportedInterfaceOrientations~ipad:
          - UIInterfaceOrientationPortrait
          - UIInterfaceOrientationPortraitUpsideDown
          - UIInterfaceOrientationLandscapeLeft
          - UIInterfaceOrientationLandscapeRight  
    dependencies:
      - package: DesignSystem
      - package: Keychain
      - package: SwiftUIIntrospect
      - package: proton_mail_uniffi

  ProtonMailTest:
    type: bundle.unit-test
    platform: iOS
    info: 
      path: iosTests/Info/Info.plist  
    sources:
      - path: iosTests
    dependencies:
      - target: ProtonMail
      - package: Nimble
    scheme:
      gatherCoverageData: true
      testTargets:
        - name: ProtonMailTest
          parallelizable: true
          randomExecutionOrder: true

  ProtonMailUITest:
    type: bundle.ui-testing
    platform: iOS
    info: 
      path: iosUITests/Info/Info.plist
    sources:
      - path: iosUITests
      - path: iosUITests/NetworkMocks
        type: resources
    dependencies:
      - target: ProtonMail
      - package: SwiftNIO
        product: NIOCore
        product: NIOHTTP1
      - package: SwiftNIOHTTP2 
        product: NIOHTTP2
    settings:
      configs:
        UITests: 
          SWIFT_ACTIVE_COMPILATION_CONDITIONS: "UITESTS"
    scheme: ProtonMailUITest

schemes:
  ProtonMailUITest:
    build:
      config: UITests
      targets:
        ProtonMail: all
        ProtonMailUITest: all
    test:
      config: UITests
      targets:
        - ProtonMailUITest
      testPlans:
        - path: iosUITests/Plans/SmokeTests.xctestplan
          defaultPlan: true
        - path: iosUITests/Plans/RegressionTests.xctestplan
      gatherCoverageData: true
      parallelizable: true
      randomExecutionOrder: true
