source "https://rubygems.org"

gem "activesupport", "7.0.8"    # latest version is currently broken
gem "cocoapods"
gem "fastlane"
gem "ffi"
# a fork that handles absolute paths, needed for code coverage when building on two different machines
gem 'slather', git: 'https://github.com/Linquas/slather.git', ref: 'f5ac241'

plugins_path = File.join(File.dirname(__FILE__), 'fastlane', 'Pluginfile')
eval_gemfile(plugins_path) if File.exist?(plugins_path)
