source 'https://github.com/CocoaPods/Specs.git'

platform :ios, '8.0'

inhibit_all_warnings!

#target 'ProtonMail','ProtonMailDev','ProtonMailTests'
def pm_pods
	pod 'Groot/ObjC', '2.0'
	pod 'OpenPGP', :path => '../OpenPGP'
	pod 'ZSSRichTextEditor', :path => '../ZSSRichTextEditor'
	pod 'AFNetworking', '3.1.0'
    pod 'AFNetworkActivityLogger', :git => 'https://github.com/AFNetworking/AFNetworkActivityLogger.git', :branch => '3_0_0'
	pod 'MBProgressHUD' , '0.9.2'
    #based on 1.0.4
    pod 'NSDate+Helper', :git => 'https://github.com/ProtonMail/nsdate-helper.git', :branch => 'master'
	pod 'UICKeyChainStore', '2.1.0'
	pod 'SWRevealViewController', '2.3.0'
	pod 'Masonry', '1.1.0'
	pod 'RHAddressBook', '1.1.1'
	pod 'UIColor+Hex', '1.0.1'
	pod 'MCSwipeTableViewCell', '~> 2.1.4'
end

def pm_extensions
    pod 'Groot/ObjC', '2.0'
    pod 'OpenPGP', :path => '../OpenPGP'
    pod 'ZSSRichTextEditor', :path => '../ZSSRichTextEditor'
    pod 'AFNetworking', '3.1.0'
    pod 'AFNetworkActivityLogger', :git => 'https://github.com/AFNetworking/AFNetworkActivityLogger.git', :branch => '3_0_0'
    #based on 1.0.4
    pod 'NSDate+Helper', :git => 'https://github.com/ProtonMail/nsdate-helper.git', :branch => 'master'
    pod 'UICKeyChainStore', '2.1.0'
    pod 'Masonry', '1.1.0'
    pod 'RHAddressBook', '1.1.1'
    pod 'UIColor+Hex', '1.0.1'
    pod 'MCSwipeTableViewCell', '~> 2.1.4'
end

def pm_push
    pod 'Groot/ObjC', '2.0'
    pod 'OpenPGP', :path => '../OpenPGP'
    pod 'AFNetworking', '3.1.0'
    pod 'AFNetworkActivityLogger', :git => 'https://github.com/AFNetworking/AFNetworkActivityLogger.git', :branch => '3_0_0'
    #based on 1.0.4
#    pod 'NSDate+Helper', :git => 'https://github.com/ProtonMail/nsdate-helper.git', :branch => 'master'
    pod 'UICKeyChainStore', '2.1.0'
#    pod 'Masonry', '1.1.0'
#    pod 'UIColor+Hex', '1.0.1'
end

target 'ProtonMail' do
	pm_pods
end

target 'ProtonMailDev' do
	pm_pods
end

target 'ProtonMailTests' do
	pm_pods
end

target 'Share' do
    pm_extensions
end

target 'ShareDev' do
    pm_extensions
end

target 'Push' do
    pm_push
end

target 'PushDev' do
    pm_push
end

post_install do | installer |
    require 'fileutils'
    FileUtils.cp_r('Pods/Target Support Files/Pods-ProtonMail/Pods-ProtonMail-Acknowledgements.plist', 'ProtonMail/Settings.bundle/Acknowledgements.plist', :remove_destination => true)
    
    installer.pods_project.targets.each do |target|
        target.build_configurations.each do |config|
            config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '8.0'
        end
    end
end
