source 'https://github.com/CocoaPods/Specs.git'

platform :ios, '8.0'

inhibit_all_warnings!

#target 'ProtonMail','ProtonMailDev','ProtonMailTests'

def pm_pods
    #pod 'Groot/ObjC', :git => 'https://github.com/zhj4478/Groot.git', :branch => 'swift2'
	pod 'Groot/ObjC', '2.0'
	pod 'OpenPGP', :path => '../OpenPGP'
	pod 'ZSSRichTextEditor', :path => '../ZSSRichTextEditor'
	pod 'AFNetworking', '3.1.0'
    #pod 'AFNetworkActivityLogger', '2.0.4'
	pod 'MBProgressHUD' , '0.9.2'
	pod 'NSDate+Helper', '1.0.0'
	pod 'UICKeyChainStore'
	pod 'SWRevealViewController', '2.3.0'
	pod 'Masonry', '1.0.0'
	pod 'RHAddressBook', '1.1.1'
	pod 'UIColor+Hex'
	pod 'MCSwipeTableViewCell', '~> 2.1.4'
end

target 'ProtonMail' do
	pm_pods
end

target 'ProtonMailDev' do
	pm_pods
end

target 'ProtonMailTests' do
	pm_pods
end

post_install do | installer |
    require 'fileutils'
    FileUtils.cp_r('Pods/Target Support Files/Pods-ProtonMail/Pods-ProtonMail-Acknowledgements.plist', 'ProtonMail/Settings.bundle/Acknowledgements.plist', :remove_destination => true)
end
