
// Objective-C API for talking to the following Go packages
//
//	go-crypto-wrapper
//
// File is generated by gomobile bind. Do not edit.
#ifndef __Pm_FRAMEWORK_H__
#define __Pm_FRAMEWORK_H__

#include "Pm.objc.h"
#include "universe.objc.h"

#endif
