// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from open_pgp.djinni

#import <Foundation/Foundation.h>


@interface PMNBCryptHash : NSObject

/**
 *base 64 *DotSlash encode
 *base 64 *DotSlash decode
 *hash
 */
+ (nonnull NSString *)hashString:(nonnull NSString *)password
                            salt:(nonnull NSString *)salt;

@end
