// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from open_pgp.djinni

#import <Foundation/Foundation.h>
@class PMNIPMEncrypt;


@interface PMNIPMEncrypt : NSObject

- (nonnull NSString *)getValue;

- (nonnull NSString *)getType;

- (nonnull NSString *)getGroup;

+ (nullable PMNIPMEncrypt *)createInstance:(nonnull NSString *)type
                                     value:(nonnull NSString *)value;

@end
