// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from open_pgp.djinni

#import <Foundation/Foundation.h>
@class PMNIUrl;


@interface PMNIUrl : NSObject

- (nonnull NSString *)getValue;

+ (nullable PMNIUrl *)createInstance;

@end
