// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from open_pgp.djinni

#import <Foundation/Foundation.h>
@class PMNIVCard;


@interface PMNIEzvcard : NSObject

+ (nullable PMNIVCard *)parseFirst:(nonnull NSString *)value;

+ (nonnull NSArray<PMNIVCard *> *)parseAll:(nonnull NSString *)value;

+ (nonnull NSString *)write:(nullable PMNIVCard *)vcard;

+ (nonnull NSString *)writeAll:(nonnull NSArray<PMNIVCard *> *)vcards;

@end
