// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from open_pgp.djinni

#import <Foundation/Foundation.h>
@class PMNIPhoto;


@interface PMNIPhoto : NSObject

+ (nullable PMNIPhoto *)createInstance:(nonnull NSData *)rawData
                                  type:(nonnull NSString *)type
                              isBinary:(BOOL)isBinary;

- (nonnull NSString *)getEncodedData;

- (nonnull NSData *)getRawData;

- (nonnull NSString *)getURL;

- (nonnull NSString *)getImageType;

- (BOOL)getIsBinary;

- (void)setPhoto:(nonnull NSData *)rawData
            type:(nonnull NSString *)type
        isBinary:(BOOL)isBinary;

@end
