// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from open_pgp.djinni

#import <Foundation/Foundation.h>
@class PMNIAddress;
@class PMNIBirthday;
@class PMNIEmail;
@class PMNIFormattedName;
@class PMNINickname;
@class PMNINote;
@class PMNIOrganization;
@class PMNIPMCustom;
@class PMNIStructuredName;
@class PMNITelephone;
@class PMNITitle;
@class PMNIUid;
@class PMNIUrl;
@class PMNIVCard;
@class PMNIVCardVersion;


@interface PMNIVCard : NSObject

- (nonnull NSArray<NSString *> *)getPropertyTypes;

- (nullable PMNIVCardVersion *)getVersion;

- (void)setVersion:(nullable PMNIVCardVersion *)version;

- (nullable PMNIFormattedName *)getFormattedName;

- (void)setFormattedName:(nullable PMNIFormattedName *)formattedName;

- (nonnull NSArray<PMNITelephone *> *)getTelephoneNumbers;

- (void)addTelephone:(nullable PMNITelephone *)cell;

- (void)setTelephones:(nonnull NSArray<PMNITelephone *> *)cells;

- (nonnull NSArray<PMNIEmail *> *)getEmails;

- (void)addEmail:(nullable PMNIEmail *)email;

/**set will replace all exsiting */
- (void)setEmails:(nonnull NSArray<PMNIEmail *> *)emails;

- (nullable PMNIUid *)getUid;

- (void)setUid:(nullable PMNIUid *)uuid;

- (nonnull NSArray<PMNIAddress *> *)getAddresses;

- (void)addAddress:(nullable PMNIAddress *)addr;

- (void)setAddresses:(nonnull NSArray<PMNIAddress *> *)addrs;

- (nullable PMNIOrganization *)getOrganization;

- (void)addOrganization:(nullable PMNIOrganization *)org;

- (void)setOrganizations:(nonnull NSArray<PMNIOrganization *> *)orgs;

- (nullable PMNINote *)getNote;

- (void)setNote:(nullable PMNINote *)note;

- (nullable PMNINickname *)getNickname;

- (void)setNickname:(nullable PMNINickname *)nickname;

- (nullable PMNITitle *)getTitle;

- (void)setTitle:(nullable PMNITitle *)title;

- (nonnull NSArray<PMNIBirthday *> *)getBirthdays;

- (void)addBirthday:(nullable PMNIBirthday *)birthday;

- (void)setBirthdays:(nonnull NSArray<PMNIBirthday *> *)birthdays;

- (nonnull NSArray<PMNIPMCustom *> *)getCustoms;

- (void)addCustom:(nullable PMNIPMCustom *)custom;

- (void)setCustoms:(nonnull NSArray<PMNIPMCustom *> *)custom;

- (nonnull NSArray<PMNIUrl *> *)getUrls;

- (void)addUrl:(nullable PMNIUrl *)url;

- (void)setUrls:(nonnull NSArray<PMNIUrl *> *)urls;

- (nullable PMNIStructuredName *)getStructuredName;

- (void)setStructuredName:(nullable PMNIStructuredName *)name;

+ (nullable PMNIVCard *)createInstance;

@end
