// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from open_pgp.djinni

#import <Foundation/Foundation.h>
@class PMNIAddress;
@class PMNIBirthday;
@class PMNIEmail;
@class PMNIFormattedName;
@class PMNINickname;
@class PMNINote;
@class PMNIOrganization;
@class PMNIPMCustom;
@class PMNIStructuredName;
@class PMNITelephone;
@class PMNITitle;
@class PMNIUid;
@class PMNIUrl;
@class PMNIVCard;
@class PMNIVCardVersion;


@interface PMNIVCard : NSObject

- (nonnull NSArray<NSString *> *)getPropertyTypes;

- (nullable PMNIVCardVersion *)getVersion;

- (void)setVersion:(nullable PMNIVCardVersion *)version;

- (nullable PMNIFormattedName *)getFormattedName;

- (void)setFormattedName:(nullable PMNIFormattedName *)formattedName;

- (nonnull NSArray<PMNITelephone *> *)getTelephoneNumbers;

- (void)addTelephone:(nullable PMNITelephone *)cell;

- (nonnull NSArray<PMNIEmail *> *)getEmails;

- (void)addEmail:(nullable PMNIEmail *)email;

- (nullable PMNIUid *)getUid;

- (void)setUid:(nullable PMNIUid *)uuid;

- (nonnull NSArray<PMNIAddress *> *)getAddresses;

- (void)addAddress:(nullable PMNIAddress *)addr;

- (nullable PMNIOrganization *)getOrganization;

- (void)addOrganization:(nullable PMNIOrganization *)org;

- (nullable PMNINote *)getNote;

- (void)addNote:(nullable PMNINote *)note;

- (nonnull NSArray<PMNINickname *> *)getNicknames;

- (nullable PMNINickname *)getNickname;

- (void)addNickname:(nullable PMNINickname *)nickname;

- (nullable PMNITitle *)getTitle;

- (void)addTitle:(nullable PMNITitle *)title;

- (nullable PMNIBirthday *)getBirthday;

- (void)addBirthday:(nullable PMNIBirthday *)birthday;

- (nonnull NSArray<PMNIPMCustom *> *)getCustoms;

- (void)addCustom:(nullable PMNIPMCustom *)custom;

- (nonnull NSArray<PMNIUrl *> *)getUrls;

- (nullable PMNIStructuredName *)getStructuredName;

+ (nullable PMNIVCard *)createInstance;

@end
