// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from open_pgp.djinni

#import <Foundation/Foundation.h>


/**static create_instance(type: string, email : string, group : string) : i_email; */
@interface PMNIKey : NSObject

- (nonnull NSString *)getKey;

- (void)setKey:(nonnull NSString *)key;

- (nonnull NSString *)getGroup;

- (void)setGroup:(nonnull NSString *)g;

- (int32_t)getPref;

- (void)setPref:(int32_t)pref;

@end
