// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from open_pgp.djinni

#import <Foundation/Foundation.h>
@class PMNIFormattedName;


/**ezvcard part */
@interface PMNIFormattedName : NSObject

- (nonnull NSString *)getLanguage;

- (void)setLanguage:(nonnull NSString *)language;

- (nonnull NSString *)getParameter:(nonnull NSString *)name;

- (nonnull NSString *)getValue;

+ (nullable PMNIFormattedName *)createInstance:(nonnull NSString *)name;

@end
