// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from open_pgp.djinni

#import <Foundation/Foundation.h>


@interface PMNLibVersion : NSObject

/**get lib version */
+ (nonnull NSString *)getLibVersion;

/**get pgp version */
+ (nonnull NSString *)getPgpVersion;

/**get vcard version */
+ (nonnull NSString *)getVcardVersion;

@end
