// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from open_pgp.djinni

#import <Foundation/Foundation.h>

@interface PMNOpenPgpKey : NSObject
- (nonnull instancetype)initWithPublicKey:(nonnull NSString *)publicKey
                               privateKey:(nonnull NSString *)privateKey;
+ (nonnull instancetype)openPgpKeyWithPublicKey:(nonnull NSString *)publicKey
                                     privateKey:(nonnull NSString *)privateKey;

@property (nonatomic, readonly, nonnull) NSString * publicKey;

@property (nonatomic, readonly, nonnull) NSString * privateKey;

@end
