// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from open_pgp.djinni

#import <Foundation/Foundation.h>

@interface PMNOpenPgpKey : NSObject
- (nonnull instancetype)initWithKeyId:(nonnull NSString *)keyId
                            publicKey:(nonnull NSString *)publicKey
                           privateKey:(nonnull NSString *)privateKey
                          fingerPrint:(nonnull NSString *)fingerPrint
                            isUpdated:(BOOL)isUpdated;
+ (nonnull instancetype)openPgpKeyWithKeyId:(nonnull NSString *)keyId
                                  publicKey:(nonnull NSString *)publicKey
                                 privateKey:(nonnull NSString *)privateKey
                                fingerPrint:(nonnull NSString *)fingerPrint
                                  isUpdated:(BOOL)isUpdated;

@property (nonatomic, readonly, nonnull) NSString * keyId;

@property (nonatomic, readonly, nonnull) NSString * publicKey;

@property (nonatomic, readonly, nonnull) NSString * privateKey;

@property (nonatomic, readonly, nonnull) NSString * fingerPrint;

/** false default only used when update keys */
@property (nonatomic, readonly) BOOL isUpdated;

@end
