// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from open_pgp.djinni

#import <Foundation/Foundation.h>

@interface PMNSrpProofs : NSObject
- (nonnull instancetype)initWithClientEphemeral:(nonnull NSData *)clientEphemeral
                                    clientProof:(nonnull NSData *)clientProof
                            expectedServerProof:(nonnull NSData *)expectedServerProof;
+ (nonnull instancetype)srpProofsWithClientEphemeral:(nonnull NSData *)clientEphemeral
                                         clientProof:(nonnull NSData *)clientProof
                                 expectedServerProof:(nonnull NSData *)expectedServerProof;

@property (nonatomic, readonly, nonnull) NSData * clientEphemeral;

@property (nonatomic, readonly, nonnull) NSData * clientProof;

@property (nonatomic, readonly, nonnull) NSData * expectedServerProof;

@end
