// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from open_pgp.djinni

#import "PMNSrpProofs.h"
#import <Foundation/Foundation.h>


@interface PMNSrpClient : NSObject

/**ExpandHash */
+ (nonnull NSData *)expandHash:(nonnull NSData *)input;

/**SRP */
+ (nonnull PMNSrpProofs *)generateProofs:(int32_t)bitLength
                             modulusRepr:(nonnull NSData *)modulusRepr
                     serverEphemeralRepr:(nonnull NSData *)serverEphemeralRepr
                      hashedPasswordRepr:(nonnull NSData *)hashedPasswordRepr;

+ (nonnull NSData *)generateVerifier:(int32_t)bitLength
                         modulusRepr:(nonnull NSData *)modulusRepr
                  hashedPasswordRepr:(nonnull NSData *)hashedPasswordRepr;

@end
