opt_out_usage

default_platform(:ios)

UNIT_TESTS_SCHEME = "ProtonMailTest"
UI_TESTS_SCHEME = "ProtonMailUITest"
UI_TESTS_DEVICE = "iPhone 15 Pro"
UNIT_TESTS_DEVICE = "iPhone 15 Pro"

CONCURRENT_WORKERS=2
MAX_CONCURRENT_SIMULATORS=2
SMOKE_PLAN_NAME="SmokeTests"
REGRESSION_PLAN_NAME="RegressionTests"

platform :ios do
  desc "Build the app"
  # Skip archiving and codesigning, until provisioning is properly set.
  lane :build do
    build_app(
      scheme: "ProtonMail",
      configuration: "Release",
      skip_codesigning: true,
      clean: true,
      skip_archive: true
    )
  end

  desc "Run unit tests"
  lane :tests do
    run_tests(
      scheme: UNIT_TESTS_SCHEME,
      devices: UNIT_TESTS_DEVICE,
      prelaunch_simulator: true,
      reset_simulator: true,
      result_bundle: true
      )
  end

  desc "Setup UI Tests assets"
    lane :setup_uitests_assets do
    sh("../scripts/uitests/setup-mock-network-assets.sh setup-remote")
    sh("../xcodegen/bin/xcodegen -s ../project.yml") # We need to do it another time to include UI tests assets.
  end

  desc "Run UI Smoke Tests"
  lane :uitests_smoke do
      run_tests(
        scheme: UI_TESTS_SCHEME,
        devices: UI_TESTS_DEVICE,
        max_concurrent_simulators: MAX_CONCURRENT_SIMULATORS,
        concurrent_workers: CONCURRENT_WORKERS,
        include_simulator_logs: true,
        prelaunch_simulator: true,
        reset_simulator: true,
        result_bundle: true,
        testplan: SMOKE_PLAN_NAME
      )
  end

  desc "Run UI Full Regression Tests"
    lane :uitests_full_regression do
      run_tests(
        scheme: UI_TESTS_SCHEME,
        devices: UI_TESTS_DEVICE,
        max_concurrent_simulators: MAX_CONCURRENT_SIMULATORS,
        concurrent_workers: CONCURRENT_WORKERS,
        include_simulator_logs: true,
        prelaunch_simulator: true,
        reset_simulator: true,
        result_bundle: true,
        testplan: REGRESSION_PLAN_NAME
      )
  end
end
