// Objective-C API for talking to gitlab.com/ProtonMail/go-pm-crypto/armor Go package.
//   gobind -lang=objc gitlab.com/ProtonMail/go-pm-crypto/armor
//
// File is generated by gobind. Do not edit.

#ifndef __Armor_H__
#define __Armor_H__

@import Foundation;
#include "Universe.objc.h"

#include "Models.objc.h"

FOUNDATION_EXPORT NSString* const ArmorARMOR_HEADER_COMMENT;
FOUNDATION_EXPORT NSString* const ArmorARMOR_HEADER_VERSION;
FOUNDATION_EXPORT NSString* const ArmorMESSAGE_HEADER;
FOUNDATION_EXPORT NSString* const ArmorPRIVATE_KEY_HEADER;
FOUNDATION_EXPORT NSString* const ArmorPUBLIC_KEY_HEADER;

FOUNDATION_EXPORT NSString* ArmorArmorKey(NSData* input, NSError** error);

FOUNDATION_EXPORT NSString* ArmorArmorWithType(NSData* input, NSString* armorType, NSError** error);

FOUNDATION_EXPORT NSString* ArmorReadClearSignedMessage(NSString* signedMessage, NSError** error);

FOUNDATION_EXPORT ModelsEncryptedSplit* ArmorSplitArmor(NSString* encrypted, NSError** error);

FOUNDATION_EXPORT NSData* ArmorUnarmor(NSString* input, NSError** error);

#endif
