// Objective-C API for talking to gitlab.com/ProtonMail/go-pm-crypto/constants Go package.
//   gobind -lang=objc gitlab.com/ProtonMail/go-pm-crypto/constants
//
// File is generated by gobind. Do not edit.

#ifndef __Constants_H__
#define __Constants_H__

@import Foundation;
#include "Universe.objc.h"


FOUNDATION_EXPORT NSString* const ConstantsVERSION;

#endif
