
// Objective-C API for talking to the following Go packages
//
//	gitlab.com/ProtonMail/go-pm-crypto/crypto
//	gitlab.com/ProtonMail/go-pm-crypto/armor
//	gitlab.com/ProtonMail/go-pm-crypto/constants
//	gitlab.com/ProtonMail/go-pm-crypto/key
//	gitlab.com/ProtonMail/go-pm-crypto/models
//	go-srp
//
// File is generated by gomobile bind. Do not edit.
#ifndef __Crypto_FRAMEWORK_H__
#define __Crypto_FRAMEWORK_H__

#include "Crypto.objc.h"
#include "Armor.objc.h"
#include "Constants.objc.h"
#include "Key.objc.h"
#include "Models.objc.h"
#include "Srp.objc.h"
#include "Universe.objc.h"

#endif
