// Objective-C API for talking to github.com/ProtonMail/gopenpgp/mobile Go package.
//   gobind -lang=objc github.com/ProtonMail/gopenpgp/mobile
//
// File is generated by gobind. Do not edit.

#ifndef __Mobile_H__
#define __Mobile_H__

@import Foundation;
#include "ref.h"
#include "Universe.objc.h"

#include "Crypto.objc.h"

@class MobileExplicitVerifyMessage;

@interface MobileExplicitVerifyMessage : NSObject <goSeqRefInterface> {
}
@property(strong, readonly) _Nonnull id _ref;

- (nonnull instancetype)initWithRef:(_Nonnull id)ref;
- (nonnull instancetype)init;
@property (nonatomic) CryptoPlainMessage* _Nullable message;
@property (nonatomic) CryptoSignatureVerificationError* _Nullable signatureVerificationError;
@end

/**
 * DecryptVerifyMessageArmored decrypts an armored PGP message given a private key and its passphrase
and verifies the embedded signature.
Returns the plain data or an error on signature verification failure.
 */
FOUNDATION_EXPORT MobileExplicitVerifyMessage* _Nullable MobileDecryptExplicitVerify(CryptoPGPMessage* _Nullable pgpMessage, CryptoKeyRing* _Nullable privateKeyRing, CryptoKeyRing* _Nullable publicKeyRing, int64_t verifyTime, NSError* _Nullable* _Nullable error);

FOUNDATION_EXPORT CryptoSignatureVerificationError* _Nullable MobileVerifyDetached(CryptoKeyRing* _Nullable publicKeyRing, CryptoPlainMessage* _Nullable message, CryptoPGPSignature* _Nullable signature, int64_t verifyTime, NSError* _Nullable* _Nullable error);

#endif
