// This file was autogenerated by some hot garbage in the `uniffi` crate.
// Trust me, you don't want to mess with it!

// swiftlint:disable all
import Foundation

// Depending on the consumer's build setup, the low-level FFI code
// might be in a separate module, or it might be compiled inline into
// this module. This is a bit of light hackery to work with both.
#if canImport(proton_mail_uniffi_ffi)
import proton_mail_uniffi_ffi
#endif

fileprivate extension RustBuffer {
    // Allocate a new buffer, copying the contents of a `UInt8` array.
    init(bytes: [UInt8]) {
        let rbuf = bytes.withUnsafeBufferPointer { ptr in
            RustBuffer.from(ptr)
        }
        self.init(capacity: rbuf.capacity, len: rbuf.len, data: rbuf.data)
    }

    static func empty() -> RustBuffer {
        RustBuffer(capacity: 0, len:0, data: nil)
    }

    static func from(_ ptr: UnsafeBufferPointer<UInt8>) -> RustBuffer {
        try! rustCall { ffi_proton_api_core_rustbuffer_from_bytes(ForeignBytes(bufferPointer: ptr), $0) }
    }

    // Frees the buffer in place.
    // The buffer must not be used after this is called.
    func deallocate() {
        try! rustCall { ffi_proton_api_core_rustbuffer_free(self, $0) }
    }
}

fileprivate extension ForeignBytes {
    init(bufferPointer: UnsafeBufferPointer<UInt8>) {
        self.init(len: Int32(bufferPointer.count), data: bufferPointer.baseAddress)
    }
}

// For every type used in the interface, we provide helper methods for conveniently
// lifting and lowering that type from C-compatible data, and for reading and writing
// values of that type in a buffer.

// Helper classes/extensions that don't change.
// Someday, this will be in a library of its own.

fileprivate extension Data {
    init(rustBuffer: RustBuffer) {
        // TODO: This copies the buffer. Can we read directly from a
        // Rust buffer?
        self.init(bytes: rustBuffer.data!, count: Int(rustBuffer.len))
    }
}

// Define reader functionality.  Normally this would be defined in a class or
// struct, but we use standalone functions instead in order to make external
// types work.
//
// With external types, one swift source file needs to be able to call the read
// method on another source file's FfiConverter, but then what visibility
// should Reader have?
// - If Reader is fileprivate, then this means the read() must also
//   be fileprivate, which doesn't work with external types.
// - If Reader is internal/public, we'll get compile errors since both source
//   files will try define the same type.
//
// Instead, the read() method and these helper functions input a tuple of data

fileprivate func createReader(data: Data) -> (data: Data, offset: Data.Index) {
    (data: data, offset: 0)
}

// Reads an integer at the current offset, in big-endian order, and advances
// the offset on success. Throws if reading the integer would move the
// offset past the end of the buffer.
fileprivate func readInt<T: FixedWidthInteger>(_ reader: inout (data: Data, offset: Data.Index)) throws -> T {
    let range = reader.offset..<reader.offset + MemoryLayout<T>.size
    guard reader.data.count >= range.upperBound else {
        throw UniffiInternalError.bufferOverflow
    }
    if T.self == UInt8.self {
        let value = reader.data[reader.offset]
        reader.offset += 1
        return value as! T
    }
    var value: T = 0
    let _ = withUnsafeMutableBytes(of: &value, { reader.data.copyBytes(to: $0, from: range)})
    reader.offset = range.upperBound
    return value.bigEndian
}

// Reads an arbitrary number of bytes, to be used to read
// raw bytes, this is useful when lifting strings
fileprivate func readBytes(_ reader: inout (data: Data, offset: Data.Index), count: Int) throws -> Array<UInt8> {
    let range = reader.offset..<(reader.offset+count)
    guard reader.data.count >= range.upperBound else {
        throw UniffiInternalError.bufferOverflow
    }
    var value = [UInt8](repeating: 0, count: count)
    value.withUnsafeMutableBufferPointer({ buffer in
        reader.data.copyBytes(to: buffer, from: range)
    })
    reader.offset = range.upperBound
    return value
}

// Reads a float at the current offset.
fileprivate func readFloat(_ reader: inout (data: Data, offset: Data.Index)) throws -> Float {
    return Float(bitPattern: try readInt(&reader))
}

// Reads a float at the current offset.
fileprivate func readDouble(_ reader: inout (data: Data, offset: Data.Index)) throws -> Double {
    return Double(bitPattern: try readInt(&reader))
}

// Indicates if the offset has reached the end of the buffer.
fileprivate func hasRemaining(_ reader: (data: Data, offset: Data.Index)) -> Bool {
    return reader.offset < reader.data.count
}

// Define writer functionality.  Normally this would be defined in a class or
// struct, but we use standalone functions instead in order to make external
// types work.  See the above discussion on Readers for details.

fileprivate func createWriter() -> [UInt8] {
    return []
}

fileprivate func writeBytes<S>(_ writer: inout [UInt8], _ byteArr: S) where S: Sequence, S.Element == UInt8 {
    writer.append(contentsOf: byteArr)
}

// Writes an integer in big-endian order.
//
// Warning: make sure what you are trying to write
// is in the correct type!
fileprivate func writeInt<T: FixedWidthInteger>(_ writer: inout [UInt8], _ value: T) {
    var value = value.bigEndian
    withUnsafeBytes(of: &value) { writer.append(contentsOf: $0) }
}

fileprivate func writeFloat(_ writer: inout [UInt8], _ value: Float) {
    writeInt(&writer, value.bitPattern)
}

fileprivate func writeDouble(_ writer: inout [UInt8], _ value: Double) {
    writeInt(&writer, value.bitPattern)
}

// Protocol for types that transfer other types across the FFI. This is
// analogous go the Rust trait of the same name.
fileprivate protocol FfiConverter {
    associatedtype FfiType
    associatedtype SwiftType

    static func lift(_ value: FfiType) throws -> SwiftType
    static func lower(_ value: SwiftType) -> FfiType
    static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> SwiftType
    static func write(_ value: SwiftType, into buf: inout [UInt8])
}

// Types conforming to `Primitive` pass themselves directly over the FFI.
fileprivate protocol FfiConverterPrimitive: FfiConverter where FfiType == SwiftType { }

extension FfiConverterPrimitive {
    public static func lift(_ value: FfiType) throws -> SwiftType {
        return value
    }

    public static func lower(_ value: SwiftType) -> FfiType {
        return value
    }
}

// Types conforming to `FfiConverterRustBuffer` lift and lower into a `RustBuffer`.
// Used for complex types where it's hard to write a custom lift/lower.
fileprivate protocol FfiConverterRustBuffer: FfiConverter where FfiType == RustBuffer {}

extension FfiConverterRustBuffer {
    public static func lift(_ buf: RustBuffer) throws -> SwiftType {
        var reader = createReader(data: Data(rustBuffer: buf))
        let value = try read(from: &reader)
        if hasRemaining(reader) {
            throw UniffiInternalError.incompleteData
        }
        buf.deallocate()
        return value
    }

    public static func lower(_ value: SwiftType) -> RustBuffer {
          var writer = createWriter()
          write(value, into: &writer)
          return RustBuffer(bytes: writer)
    }
}
// An error type for FFI errors. These errors occur at the UniFFI level, not
// the library level.
fileprivate enum UniffiInternalError: LocalizedError {
    case bufferOverflow
    case incompleteData
    case unexpectedOptionalTag
    case unexpectedEnumCase
    case unexpectedNullPointer
    case unexpectedRustCallStatusCode
    case unexpectedRustCallError
    case unexpectedStaleHandle
    case rustPanic(_ message: String)

    public var errorDescription: String? {
        switch self {
        case .bufferOverflow: return "Reading the requested value would read past the end of the buffer"
        case .incompleteData: return "The buffer still has data after lifting its containing value"
        case .unexpectedOptionalTag: return "Unexpected optional tag; should be 0 or 1"
        case .unexpectedEnumCase: return "Raw enum value doesn't match any cases"
        case .unexpectedNullPointer: return "Raw pointer value was null"
        case .unexpectedRustCallStatusCode: return "Unexpected RustCallStatus code"
        case .unexpectedRustCallError: return "CALL_ERROR but no errorClass specified"
        case .unexpectedStaleHandle: return "The object in the handle map has been dropped already"
        case let .rustPanic(message): return message
        }
    }
}

fileprivate extension NSLock {
    func withLock<T>(f: () throws -> T) rethrows -> T {
        self.lock()
        defer { self.unlock() }
        return try f()
    }
}

fileprivate let CALL_SUCCESS: Int8 = 0
fileprivate let CALL_ERROR: Int8 = 1
fileprivate let CALL_UNEXPECTED_ERROR: Int8 = 2
fileprivate let CALL_CANCELLED: Int8 = 3

fileprivate extension RustCallStatus {
    init() {
        self.init(
            code: CALL_SUCCESS,
            errorBuf: RustBuffer.init(
                capacity: 0,
                len: 0,
                data: nil
            )
        )
    }
}

private func rustCall<T>(_ callback: (UnsafeMutablePointer<RustCallStatus>) -> T) throws -> T {
    try makeRustCall(callback, errorHandler: nil)
}

private func rustCallWithError<T>(
    _ errorHandler: @escaping (RustBuffer) throws -> Error,
    _ callback: (UnsafeMutablePointer<RustCallStatus>) -> T) throws -> T {
    try makeRustCall(callback, errorHandler: errorHandler)
}

private func makeRustCall<T>(
    _ callback: (UnsafeMutablePointer<RustCallStatus>) -> T,
    errorHandler: ((RustBuffer) throws -> Error)?
) throws -> T {
    uniffiEnsureInitialized()
    var callStatus = RustCallStatus.init()
    let returnedVal = callback(&callStatus)
    try uniffiCheckCallStatus(callStatus: callStatus, errorHandler: errorHandler)
    return returnedVal
}

private func uniffiCheckCallStatus(
    callStatus: RustCallStatus,
    errorHandler: ((RustBuffer) throws -> Error)?
) throws {
    switch callStatus.code {
        case CALL_SUCCESS:
            return

        case CALL_ERROR:
            if let errorHandler = errorHandler {
                throw try errorHandler(callStatus.errorBuf)
            } else {
                callStatus.errorBuf.deallocate()
                throw UniffiInternalError.unexpectedRustCallError
            }

        case CALL_UNEXPECTED_ERROR:
            // When the rust code sees a panic, it tries to construct a RustBuffer
            // with the message.  But if that code panics, then it just sends back
            // an empty buffer.
            if callStatus.errorBuf.len > 0 {
                throw UniffiInternalError.rustPanic(try FfiConverterString.lift(callStatus.errorBuf))
            } else {
                callStatus.errorBuf.deallocate()
                throw UniffiInternalError.rustPanic("Rust panic")
            }

        case CALL_CANCELLED:
            fatalError("Cancellation not supported yet")

        default:
            throw UniffiInternalError.unexpectedRustCallStatusCode
    }
}

private func uniffiTraitInterfaceCall<T>(
    callStatus: UnsafeMutablePointer<RustCallStatus>,
    makeCall: () throws -> T,
    writeReturn: (T) -> ()
) {
    do {
        try writeReturn(makeCall())
    } catch let error {
        callStatus.pointee.code = CALL_UNEXPECTED_ERROR
        callStatus.pointee.errorBuf = FfiConverterString.lower(String(describing: error))
    }
}

private func uniffiTraitInterfaceCallWithError<T, E>(
    callStatus: UnsafeMutablePointer<RustCallStatus>,
    makeCall: () throws -> T,
    writeReturn: (T) -> (),
    lowerError: (E) -> RustBuffer
) {
    do {
        try writeReturn(makeCall())
    } catch let error as E {
        callStatus.pointee.code = CALL_ERROR
        callStatus.pointee.errorBuf = lowerError(error)
    } catch {
        callStatus.pointee.code = CALL_UNEXPECTED_ERROR
        callStatus.pointee.errorBuf = FfiConverterString.lower(String(describing: error))
    }
}
fileprivate class UniffiHandleMap<T> {
    private var map: [UInt64: T] = [:]
    private let lock = NSLock()
    private var currentHandle: UInt64 = 1

    func insert(obj: T) -> UInt64 {
        lock.withLock {
            let handle = currentHandle
            currentHandle += 1
            map[handle] = obj
            return handle
        }
    }

     func get(handle: UInt64) throws -> T {
        try lock.withLock {
            guard let obj = map[handle] else {
                throw UniffiInternalError.unexpectedStaleHandle
            }
            return obj
        }
    }

    @discardableResult
    func remove(handle: UInt64) throws -> T {
        try lock.withLock {
            guard let obj = map.removeValue(forKey: handle) else {
                throw UniffiInternalError.unexpectedStaleHandle
            }
            return obj
        }
    }

    var count: Int {
        get {
            map.count
        }
    }
}


// Public interface members begin here.


fileprivate struct FfiConverterBool : FfiConverter {
    typealias FfiType = Int8
    typealias SwiftType = Bool

    public static func lift(_ value: Int8) throws -> Bool {
        return value != 0
    }

    public static func lower(_ value: Bool) -> Int8 {
        return value ? 1 : 0
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> Bool {
        return try lift(readInt(&buf))
    }

    public static func write(_ value: Bool, into buf: inout [UInt8]) {
        writeInt(&buf, lower(value))
    }
}

fileprivate struct FfiConverterString: FfiConverter {
    typealias SwiftType = String
    typealias FfiType = RustBuffer

    public static func lift(_ value: RustBuffer) throws -> String {
        defer {
            value.deallocate()
        }
        if value.data == nil {
            return String()
        }
        let bytes = UnsafeBufferPointer<UInt8>(start: value.data!, count: Int(value.len))
        return String(bytes: bytes, encoding: String.Encoding.utf8)!
    }

    public static func lower(_ value: String) -> RustBuffer {
        return value.utf8CString.withUnsafeBufferPointer { ptr in
            // The swift string gives us int8_t, we want uint8_t.
            ptr.withMemoryRebound(to: UInt8.self) { ptr in
                // The swift string gives us a trailing null byte, we don't want it.
                let buf = UnsafeBufferPointer(rebasing: ptr.prefix(upTo: ptr.count - 1))
                return RustBuffer.from(buf)
            }
        }
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> String {
        let len: Int32 = try readInt(&buf)
        return String(bytes: try readBytes(&buf, count: Int(len)), encoding: String.Encoding.utf8)!
    }

    public static func write(_ value: String, into buf: inout [UInt8]) {
        let len = Int32(value.utf8.count)
        writeInt(&buf, len)
        writeBytes(&buf, value.utf8)
    }
}


/**
 * API Environment Configuration
 */
public struct ApiEnvConfig {
    public var appVersion: String
    public var baseUrl: String
    public var userAgent: String
    public var allowHttp: Bool
    public var skipSrpProofValidation: Bool

    // Default memberwise initializers are never public by default, so we
    // declare one manually.
    public init(appVersion: String, baseUrl: String, userAgent: String, allowHttp: Bool, skipSrpProofValidation: Bool) {
        self.appVersion = appVersion
        self.baseUrl = baseUrl
        self.userAgent = userAgent
        self.allowHttp = allowHttp
        self.skipSrpProofValidation = skipSrpProofValidation
    }
}


extension ApiEnvConfig: Sendable {} 
extension ApiEnvConfig: Equatable, Hashable {
    public static func ==(lhs: ApiEnvConfig, rhs: ApiEnvConfig) -> Bool {
        if lhs.appVersion != rhs.appVersion {
            return false
        }
        if lhs.baseUrl != rhs.baseUrl {
            return false
        }
        if lhs.userAgent != rhs.userAgent {
            return false
        }
        if lhs.allowHttp != rhs.allowHttp {
            return false
        }
        if lhs.skipSrpProofValidation != rhs.skipSrpProofValidation {
            return false
        }
        return true
    }

    public func hash(into hasher: inout Hasher) {
        hasher.combine(appVersion)
        hasher.combine(baseUrl)
        hasher.combine(userAgent)
        hasher.combine(allowHttp)
        hasher.combine(skipSrpProofValidation)
    }
}


public struct FfiConverterTypeAPIEnvConfig: FfiConverterRustBuffer {
    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> ApiEnvConfig {
        return
            try ApiEnvConfig(
                appVersion: FfiConverterString.read(from: &buf), 
                baseUrl: FfiConverterString.read(from: &buf), 
                userAgent: FfiConverterString.read(from: &buf), 
                allowHttp: FfiConverterBool.read(from: &buf), 
                skipSrpProofValidation: FfiConverterBool.read(from: &buf)
        )
    }

    public static func write(_ value: ApiEnvConfig, into buf: inout [UInt8]) {
        FfiConverterString.write(value.appVersion, into: &buf)
        FfiConverterString.write(value.baseUrl, into: &buf)
        FfiConverterString.write(value.userAgent, into: &buf)
        FfiConverterBool.write(value.allowHttp, into: &buf)
        FfiConverterBool.write(value.skipSrpProofValidation, into: &buf)
    }
}


public func FfiConverterTypeAPIEnvConfig_lift(_ buf: RustBuffer) throws -> ApiEnvConfig {
    return try FfiConverterTypeAPIEnvConfig.lift(buf)
}

public func FfiConverterTypeAPIEnvConfig_lower(_ value: ApiEnvConfig) -> RustBuffer {
    return FfiConverterTypeAPIEnvConfig.lower(value)
}


public struct Dummy {
    public var userId: UserId
    public var uid: Uid

    // Default memberwise initializers are never public by default, so we
    // declare one manually.
    public init(userId: UserId, uid: Uid) {
        self.userId = userId
        self.uid = uid
    }
}


extension Dummy: Sendable {} 
extension Dummy: Equatable, Hashable {
    public static func ==(lhs: Dummy, rhs: Dummy) -> Bool {
        if lhs.userId != rhs.userId {
            return false
        }
        if lhs.uid != rhs.uid {
            return false
        }
        return true
    }

    public func hash(into hasher: inout Hasher) {
        hasher.combine(userId)
        hasher.combine(uid)
    }
}


public struct FfiConverterTypeDummy: FfiConverterRustBuffer {
    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> Dummy {
        return
            try Dummy(
                userId: FfiConverterTypeUserId.read(from: &buf), 
                uid: FfiConverterTypeUid.read(from: &buf)
        )
    }

    public static func write(_ value: Dummy, into buf: inout [UInt8]) {
        FfiConverterTypeUserId.write(value.userId, into: &buf)
        FfiConverterTypeUid.write(value.uid, into: &buf)
    }
}


public func FfiConverterTypeDummy_lift(_ buf: RustBuffer) throws -> Dummy {
    return try FfiConverterTypeDummy.lift(buf)
}

public func FfiConverterTypeDummy_lower(_ value: Dummy) -> RustBuffer {
    return FfiConverterTypeDummy.lower(value)
}

// Note that we don't yet support `indirect` for enums.
// See https://github.com/mozilla/uniffi-rs/issues/396 for further discussion.

public enum AddressStatus : UInt8 {
    
    case disabled = 0
    case enabled = 1
    case deleting = 2
}


public struct FfiConverterTypeAddressStatus: FfiConverterRustBuffer {
    typealias SwiftType = AddressStatus

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> AddressStatus {
        let variant: Int32 = try readInt(&buf)
        switch variant {
        
        case 1: return .disabled
        
        case 2: return .enabled
        
        case 3: return .deleting
        
        default: throw UniffiInternalError.unexpectedEnumCase
        }
    }

    public static func write(_ value: AddressStatus, into buf: inout [UInt8]) {
        switch value {
        
        
        case .disabled:
            writeInt(&buf, Int32(1))
        
        
        case .enabled:
            writeInt(&buf, Int32(2))
        
        
        case .deleting:
            writeInt(&buf, Int32(3))
        
        }
    }
}


public func FfiConverterTypeAddressStatus_lift(_ buf: RustBuffer) throws -> AddressStatus {
    return try FfiConverterTypeAddressStatus.lift(buf)
}

public func FfiConverterTypeAddressStatus_lower(_ value: AddressStatus) -> RustBuffer {
    return FfiConverterTypeAddressStatus.lower(value)
}


extension AddressStatus: Sendable {} 
extension AddressStatus: Equatable, Hashable {}



// Note that we don't yet support `indirect` for enums.
// See https://github.com/mozilla/uniffi-rs/issues/396 for further discussion.

public enum AddressType : UInt8 {
    
    case original = 1
    case alias = 2
    case custom = 3
    case premium = 4
    case external = 5
}


public struct FfiConverterTypeAddressType: FfiConverterRustBuffer {
    typealias SwiftType = AddressType

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> AddressType {
        let variant: Int32 = try readInt(&buf)
        switch variant {
        
        case 1: return .original
        
        case 2: return .alias
        
        case 3: return .custom
        
        case 4: return .premium
        
        case 5: return .external
        
        default: throw UniffiInternalError.unexpectedEnumCase
        }
    }

    public static func write(_ value: AddressType, into buf: inout [UInt8]) {
        switch value {
        
        
        case .original:
            writeInt(&buf, Int32(1))
        
        
        case .alias:
            writeInt(&buf, Int32(2))
        
        
        case .custom:
            writeInt(&buf, Int32(3))
        
        
        case .premium:
            writeInt(&buf, Int32(4))
        
        
        case .external:
            writeInt(&buf, Int32(5))
        
        }
    }
}


public func FfiConverterTypeAddressType_lift(_ buf: RustBuffer) throws -> AddressType {
    return try FfiConverterTypeAddressType.lift(buf)
}

public func FfiConverterTypeAddressType_lower(_ value: AddressType) -> RustBuffer {
    return FfiConverterTypeAddressType.lower(value)
}


extension AddressType: Sendable {} 
extension AddressType: Equatable, Hashable {}



// Note that we don't yet support `indirect` for enums.
// See https://github.com/mozilla/uniffi-rs/issues/396 for further discussion.

public enum DateFormat : UInt8 {
    
    case `default` = 0
    case ddmmyyyy = 1
    case mmddyyyy = 2
    case yyyymmdd = 3
}


public struct FfiConverterTypeDateFormat: FfiConverterRustBuffer {
    typealias SwiftType = DateFormat

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> DateFormat {
        let variant: Int32 = try readInt(&buf)
        switch variant {
        
        case 1: return .`default`
        
        case 2: return .ddmmyyyy
        
        case 3: return .mmddyyyy
        
        case 4: return .yyyymmdd
        
        default: throw UniffiInternalError.unexpectedEnumCase
        }
    }

    public static func write(_ value: DateFormat, into buf: inout [UInt8]) {
        switch value {
        
        
        case .`default`:
            writeInt(&buf, Int32(1))
        
        
        case .ddmmyyyy:
            writeInt(&buf, Int32(2))
        
        
        case .mmddyyyy:
            writeInt(&buf, Int32(3))
        
        
        case .yyyymmdd:
            writeInt(&buf, Int32(4))
        
        }
    }
}


public func FfiConverterTypeDateFormat_lift(_ buf: RustBuffer) throws -> DateFormat {
    return try FfiConverterTypeDateFormat.lift(buf)
}

public func FfiConverterTypeDateFormat_lower(_ value: DateFormat) -> RustBuffer {
    return FfiConverterTypeDateFormat.lower(value)
}


extension DateFormat: Sendable {} 
extension DateFormat: Equatable, Hashable {}



// Note that we don't yet support `indirect` for enums.
// See https://github.com/mozilla/uniffi-rs/issues/396 for further discussion.

public enum Density : UInt8 {
    
    case comfortable = 0
    case compact = 1
}


public struct FfiConverterTypeDensity: FfiConverterRustBuffer {
    typealias SwiftType = Density

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> Density {
        let variant: Int32 = try readInt(&buf)
        switch variant {
        
        case 1: return .comfortable
        
        case 2: return .compact
        
        default: throw UniffiInternalError.unexpectedEnumCase
        }
    }

    public static func write(_ value: Density, into buf: inout [UInt8]) {
        switch value {
        
        
        case .comfortable:
            writeInt(&buf, Int32(1))
        
        
        case .compact:
            writeInt(&buf, Int32(2))
        
        }
    }
}


public func FfiConverterTypeDensity_lift(_ buf: RustBuffer) throws -> Density {
    return try FfiConverterTypeDensity.lift(buf)
}

public func FfiConverterTypeDensity_lower(_ value: Density) -> RustBuffer {
    return FfiConverterTypeDensity.lower(value)
}


extension Density: Sendable {} 
extension Density: Equatable, Hashable {}



// Note that we don't yet support `indirect` for enums.
// See https://github.com/mozilla/uniffi-rs/issues/396 for further discussion.

public enum EarlyAccess : UInt8 {
    
    case regular = 0
    case beta = 1
}


public struct FfiConverterTypeEarlyAccess: FfiConverterRustBuffer {
    typealias SwiftType = EarlyAccess

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> EarlyAccess {
        let variant: Int32 = try readInt(&buf)
        switch variant {
        
        case 1: return .regular
        
        case 2: return .beta
        
        default: throw UniffiInternalError.unexpectedEnumCase
        }
    }

    public static func write(_ value: EarlyAccess, into buf: inout [UInt8]) {
        switch value {
        
        
        case .regular:
            writeInt(&buf, Int32(1))
        
        
        case .beta:
            writeInt(&buf, Int32(2))
        
        }
    }
}


public func FfiConverterTypeEarlyAccess_lift(_ buf: RustBuffer) throws -> EarlyAccess {
    return try FfiConverterTypeEarlyAccess.lift(buf)
}

public func FfiConverterTypeEarlyAccess_lower(_ value: EarlyAccess) -> RustBuffer {
    return FfiConverterTypeEarlyAccess.lower(value)
}


extension EarlyAccess: Sendable {} 
extension EarlyAccess: Equatable, Hashable {}



// Note that we don't yet support `indirect` for enums.
// See https://github.com/mozilla/uniffi-rs/issues/396 for further discussion.

public enum LogAuth : UInt8 {
    
    case disabled = 0
    case basic = 1
    case advanced = 2
}


public struct FfiConverterTypeLogAuth: FfiConverterRustBuffer {
    typealias SwiftType = LogAuth

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> LogAuth {
        let variant: Int32 = try readInt(&buf)
        switch variant {
        
        case 1: return .disabled
        
        case 2: return .basic
        
        case 3: return .advanced
        
        default: throw UniffiInternalError.unexpectedEnumCase
        }
    }

    public static func write(_ value: LogAuth, into buf: inout [UInt8]) {
        switch value {
        
        
        case .disabled:
            writeInt(&buf, Int32(1))
        
        
        case .basic:
            writeInt(&buf, Int32(2))
        
        
        case .advanced:
            writeInt(&buf, Int32(3))
        
        }
    }
}


public func FfiConverterTypeLogAuth_lift(_ buf: RustBuffer) throws -> LogAuth {
    return try FfiConverterTypeLogAuth.lift(buf)
}

public func FfiConverterTypeLogAuth_lower(_ value: LogAuth) -> RustBuffer {
    return FfiConverterTypeLogAuth.lower(value)
}


extension LogAuth: Sendable {} 
extension LogAuth: Equatable, Hashable {}



// Note that we don't yet support `indirect` for enums.
// See https://github.com/mozilla/uniffi-rs/issues/396 for further discussion.
/**
 * Errors that may occur during an HTTP request, mostly related to network.
 */

public enum RequestError {
    
    case api
    case redirect
    case timeout
    case connection
    case request
    case encodeOrDecode
    case other
}


public struct FfiConverterTypeRequestError: FfiConverterRustBuffer {
    typealias SwiftType = RequestError

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> RequestError {
        let variant: Int32 = try readInt(&buf)
        switch variant {
        
        case 1: return .api
        
        case 2: return .redirect
        
        case 3: return .timeout
        
        case 4: return .connection
        
        case 5: return .request
        
        case 6: return .encodeOrDecode
        
        case 7: return .other
        
        default: throw UniffiInternalError.unexpectedEnumCase
        }
    }

    public static func write(_ value: RequestError, into buf: inout [UInt8]) {
        switch value {
        
        
        case .api:
            writeInt(&buf, Int32(1))
        
        
        case .redirect:
            writeInt(&buf, Int32(2))
        
        
        case .timeout:
            writeInt(&buf, Int32(3))
        
        
        case .connection:
            writeInt(&buf, Int32(4))
        
        
        case .request:
            writeInt(&buf, Int32(5))
        
        
        case .encodeOrDecode:
            writeInt(&buf, Int32(6))
        
        
        case .other:
            writeInt(&buf, Int32(7))
        
        }
    }
}


public func FfiConverterTypeRequestError_lift(_ buf: RustBuffer) throws -> RequestError {
    return try FfiConverterTypeRequestError.lift(buf)
}

public func FfiConverterTypeRequestError_lower(_ value: RequestError) -> RustBuffer {
    return FfiConverterTypeRequestError.lower(value)
}


extension RequestError: Sendable {} 
extension RequestError: Equatable, Hashable {}



// Note that we don't yet support `indirect` for enums.
// See https://github.com/mozilla/uniffi-rs/issues/396 for further discussion.

public enum TfaStatus : UInt8 {
    
    case none = 0
    case totp = 1
    case fido2 = 2
    case totpOrFido2 = 3
}


public struct FfiConverterTypeTFAStatus: FfiConverterRustBuffer {
    typealias SwiftType = TfaStatus

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> TfaStatus {
        let variant: Int32 = try readInt(&buf)
        switch variant {
        
        case 1: return .none
        
        case 2: return .totp
        
        case 3: return .fido2
        
        case 4: return .totpOrFido2
        
        default: throw UniffiInternalError.unexpectedEnumCase
        }
    }

    public static func write(_ value: TfaStatus, into buf: inout [UInt8]) {
        switch value {
        
        
        case .none:
            writeInt(&buf, Int32(1))
        
        
        case .totp:
            writeInt(&buf, Int32(2))
        
        
        case .fido2:
            writeInt(&buf, Int32(3))
        
        
        case .totpOrFido2:
            writeInt(&buf, Int32(4))
        
        }
    }
}


public func FfiConverterTypeTFAStatus_lift(_ buf: RustBuffer) throws -> TfaStatus {
    return try FfiConverterTypeTFAStatus.lift(buf)
}

public func FfiConverterTypeTFAStatus_lower(_ value: TfaStatus) -> RustBuffer {
    return FfiConverterTypeTFAStatus.lower(value)
}


extension TfaStatus: Sendable {} 
extension TfaStatus: Equatable, Hashable {}



// Note that we don't yet support `indirect` for enums.
// See https://github.com/mozilla/uniffi-rs/issues/396 for further discussion.

public enum TimeFormat : UInt8 {
    
    case `default` = 0
    case h24 = 1
    case h12 = 2
}


public struct FfiConverterTypeTimeFormat: FfiConverterRustBuffer {
    typealias SwiftType = TimeFormat

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> TimeFormat {
        let variant: Int32 = try readInt(&buf)
        switch variant {
        
        case 1: return .`default`
        
        case 2: return .h24
        
        case 3: return .h12
        
        default: throw UniffiInternalError.unexpectedEnumCase
        }
    }

    public static func write(_ value: TimeFormat, into buf: inout [UInt8]) {
        switch value {
        
        
        case .`default`:
            writeInt(&buf, Int32(1))
        
        
        case .h24:
            writeInt(&buf, Int32(2))
        
        
        case .h12:
            writeInt(&buf, Int32(3))
        
        }
    }
}


public func FfiConverterTypeTimeFormat_lift(_ buf: RustBuffer) throws -> TimeFormat {
    return try FfiConverterTypeTimeFormat.lift(buf)
}

public func FfiConverterTypeTimeFormat_lower(_ value: TimeFormat) -> RustBuffer {
    return FfiConverterTypeTimeFormat.lower(value)
}


extension TimeFormat: Sendable {} 
extension TimeFormat: Equatable, Hashable {}



// Note that we don't yet support `indirect` for enums.
// See https://github.com/mozilla/uniffi-rs/issues/396 for further discussion.

public enum UserMnemonicStatus : UInt8 {
    
    case disabled = 0
    case enabledButNotSet = 1
    case enabledNeedsReActivation = 2
    case enabledAndSet = 3
    case unknown = 4
}


public struct FfiConverterTypeUserMnemonicStatus: FfiConverterRustBuffer {
    typealias SwiftType = UserMnemonicStatus

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> UserMnemonicStatus {
        let variant: Int32 = try readInt(&buf)
        switch variant {
        
        case 1: return .disabled
        
        case 2: return .enabledButNotSet
        
        case 3: return .enabledNeedsReActivation
        
        case 4: return .enabledAndSet
        
        case 5: return .unknown
        
        default: throw UniffiInternalError.unexpectedEnumCase
        }
    }

    public static func write(_ value: UserMnemonicStatus, into buf: inout [UInt8]) {
        switch value {
        
        
        case .disabled:
            writeInt(&buf, Int32(1))
        
        
        case .enabledButNotSet:
            writeInt(&buf, Int32(2))
        
        
        case .enabledNeedsReActivation:
            writeInt(&buf, Int32(3))
        
        
        case .enabledAndSet:
            writeInt(&buf, Int32(4))
        
        
        case .unknown:
            writeInt(&buf, Int32(5))
        
        }
    }
}


public func FfiConverterTypeUserMnemonicStatus_lift(_ buf: RustBuffer) throws -> UserMnemonicStatus {
    return try FfiConverterTypeUserMnemonicStatus.lift(buf)
}

public func FfiConverterTypeUserMnemonicStatus_lower(_ value: UserMnemonicStatus) -> RustBuffer {
    return FfiConverterTypeUserMnemonicStatus.lower(value)
}


extension UserMnemonicStatus: Sendable {} 
extension UserMnemonicStatus: Equatable, Hashable {}



// Note that we don't yet support `indirect` for enums.
// See https://github.com/mozilla/uniffi-rs/issues/396 for further discussion.

public enum UserType : UInt8 {
    
    case proton = 1
    case managed = 2
    case external = 3
}


public struct FfiConverterTypeUserType: FfiConverterRustBuffer {
    typealias SwiftType = UserType

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> UserType {
        let variant: Int32 = try readInt(&buf)
        switch variant {
        
        case 1: return .proton
        
        case 2: return .managed
        
        case 3: return .external
        
        default: throw UniffiInternalError.unexpectedEnumCase
        }
    }

    public static func write(_ value: UserType, into buf: inout [UInt8]) {
        switch value {
        
        
        case .proton:
            writeInt(&buf, Int32(1))
        
        
        case .managed:
            writeInt(&buf, Int32(2))
        
        
        case .external:
            writeInt(&buf, Int32(3))
        
        }
    }
}


public func FfiConverterTypeUserType_lift(_ buf: RustBuffer) throws -> UserType {
    return try FfiConverterTypeUserType.lift(buf)
}

public func FfiConverterTypeUserType_lower(_ value: UserType) -> RustBuffer {
    return FfiConverterTypeUserType.lower(value)
}


extension UserType: Sendable {} 
extension UserType: Equatable, Hashable {}



// Note that we don't yet support `indirect` for enums.
// See https://github.com/mozilla/uniffi-rs/issues/396 for further discussion.

public enum WeekStart : UInt8 {
    
    case `default` = 0
    case monday = 1
    case saturday = 6
    case sunday = 7
}


public struct FfiConverterTypeWeekStart: FfiConverterRustBuffer {
    typealias SwiftType = WeekStart

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> WeekStart {
        let variant: Int32 = try readInt(&buf)
        switch variant {
        
        case 1: return .`default`
        
        case 2: return .monday
        
        case 3: return .saturday
        
        case 4: return .sunday
        
        default: throw UniffiInternalError.unexpectedEnumCase
        }
    }

    public static func write(_ value: WeekStart, into buf: inout [UInt8]) {
        switch value {
        
        
        case .`default`:
            writeInt(&buf, Int32(1))
        
        
        case .monday:
            writeInt(&buf, Int32(2))
        
        
        case .saturday:
            writeInt(&buf, Int32(3))
        
        
        case .sunday:
            writeInt(&buf, Int32(4))
        
        }
    }
}


public func FfiConverterTypeWeekStart_lift(_ buf: RustBuffer) throws -> WeekStart {
    return try FfiConverterTypeWeekStart.lift(buf)
}

public func FfiConverterTypeWeekStart_lower(_ value: WeekStart) -> RustBuffer {
    return FfiConverterTypeWeekStart.lower(value)
}


extension WeekStart: Sendable {} 
extension WeekStart: Equatable, Hashable {}




/**
 * Typealias from the type name used in the UDL file to the builtin type.  This
 * is needed because the UDL type name is used in function/method signatures.
 */
public typealias Uid = String
public struct FfiConverterTypeUid: FfiConverter {
    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> Uid {
        return try FfiConverterString.read(from: &buf)
    }

    public static func write(_ value: Uid, into buf: inout [UInt8]) {
        return FfiConverterString.write(value, into: &buf)
    }

    public static func lift(_ value: RustBuffer) throws -> Uid {
        return try FfiConverterString.lift(value)
    }

    public static func lower(_ value: Uid) -> RustBuffer {
        return FfiConverterString.lower(value)
    }
}


public func FfiConverterTypeUid_lift(_ value: RustBuffer) throws -> Uid {
    return try FfiConverterTypeUid.lift(value)
}

public func FfiConverterTypeUid_lower(_ value: Uid) -> RustBuffer {
    return FfiConverterTypeUid.lower(value)
}



/**
 * Typealias from the type name used in the UDL file to the builtin type.  This
 * is needed because the UDL type name is used in function/method signatures.
 */
public typealias UserId = String
public struct FfiConverterTypeUserId: FfiConverter {
    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> UserId {
        return try FfiConverterString.read(from: &buf)
    }

    public static func write(_ value: UserId, into buf: inout [UInt8]) {
        return FfiConverterString.write(value, into: &buf)
    }

    public static func lift(_ value: RustBuffer) throws -> UserId {
        return try FfiConverterString.lift(value)
    }

    public static func lower(_ value: UserId) -> RustBuffer {
        return FfiConverterString.lower(value)
    }
}


public func FfiConverterTypeUserId_lift(_ value: RustBuffer) throws -> UserId {
    return try FfiConverterTypeUserId.lift(value)
}

public func FfiConverterTypeUserId_lower(_ value: UserId) -> RustBuffer {
    return FfiConverterTypeUserId.lower(value)
}


private enum InitializationResult {
    case ok
    case contractVersionMismatch
    case apiChecksumMismatch
}
// Use a global variables to perform the versioning checks. Swift ensures that
// the code inside is only computed once.
private var initializationResult: InitializationResult {
    // Get the bindings contract version from our ComponentInterface
    let bindings_contract_version = 26
    // Get the scaffolding contract version by calling the into the dylib
    let scaffolding_contract_version = ffi_proton_api_core_uniffi_contract_version()
    if bindings_contract_version != scaffolding_contract_version {
        return InitializationResult.contractVersionMismatch
    }

    return InitializationResult.ok
}

private func uniffiEnsureInitialized() {
    switch initializationResult {
    case .ok:
        break
    case .contractVersionMismatch:
        fatalError("UniFFI contract version mismatch: try cleaning and rebuilding your project")
    case .apiChecksumMismatch:
        fatalError("UniFFI API checksum mismatch: try cleaning and rebuilding your project")
    }
}

// swiftlint:enable all