
// Objective-C API for talking to the following Go packages
//
//	go-srp
//
// File is generated by gomobile bind. Do not edit.
#ifndef __Srp_FRAMEWORK_H__
#define __Srp_FRAMEWORK_H__

#include "Srp.objc.h"
#include "Universe.objc.h"

#endif
