
// Objective-C API for talking to the following Go packages
//
//	test
//
// File is generated by gomobile bind. Do not edit.
#ifndef __Greeter_FRAMEWORK_H__
#define __Greeter_FRAMEWORK_H__

#include "Greeter.objc.h"
#include "universe.objc.h"

#endif
