include:
  - project: "translations/generator"
    ref: master
    file:
      - "/jobs/sync-crowdin.gitlab-ci.yml"
      - "/jobs/commit-locales.gitlab-ci.yml"

# This job grabs translations from I18N_SYNC_BRANCH and sends them to Crowdin
i18n-sync-crowdin:
  needs: []
  dependencies: []
  variables:
    I18N_SYNC_CROWDIN_PROJECT: "apple-mail-v4"
    I18N_SYNC_BRANCH: "develop"
  extends: .i18n-sync-crowdin-shared-apple

# This job creates the MR with updated translations in our repo
i18n-commit-locales:
  variables:
    I18N_COMMIT_CROWDIN_PROJECT: "apple-mail-v4"
    I18N_COMMIT_BRANCH_PUSH: "develop"
    I18N_COMMIT_BRANCH_ALLOWED: "develop"
  extends: .i18n-commit-locales-shared-apple2
